### ISSUE TITLE
[Help] Corrupted `.jpg.features.npz` file

### ISSUE THREAD

**Issue by Adrien-ANTON-LUDWIG** [mapillary/OpenSfM#1005]
Hi! 👋

First of all, thank you for this awesome tool! 🙏
I use it through [ODM][https://github.com/OpenDroneMap/ODM). I'm currently working on my first drone mapping project to create a 3D model of a building for heritage conservation. If you're interested, you can see [this post on the ODM forum](https://community.opendronemap.org/t/post-processing-after-odm/16314).
I already processed the dataset with success. I'm trying again with better parameters.

I encountered a corruption error at the `compute_statistics` step on a `<image_name>.jpg.features.npz` file.

<details>
  <summary>Stack trace</summary>
  
```python
[INFO]    running "/code/SuperBuild/install/bin/opensfm/bin/opensfm" compute_statistics --diagram_max_points 100000 "/datasets/whole_hdp_features/opensfm"
Traceback (most recent call last):
  File "/code/SuperBuild/install/bin/opensfm/bin/opensfm_main.py", line 25, in <module>
    commands.command_runner(
  File "/code/SuperBuild/install/bin/opensfm/opensfm/commands/command_runner.py", line 38, in command_runner
    command.run(data, args)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/commands/command.py", line 13, in run
    self.run_impl(data, args)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/commands/compute_statistics.py", line 12, in run_impl
    compute_statistics.run_dataset(dataset, args.diagram_max_points)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/actions/compute_statistics.py", line 25, in run_dataset
    stats_dict = stats.compute_all_statistics(data, tracks_manager, reconstructions)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/stats.py", line 632, in compute_all_statistics
    stats["features_statistics"] = features_statistics(
  File "/code/SuperBuild/install/bin/opensfm/opensfm/stats.py", line 520, in features_statistics
    features_data = feature_loader.instance.load_all_data(data, im, False, False)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 111, in load_all_data
    features_data = self._load_all_data_unmasked(data, image)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 154, in _load_all_data_unmasked
    return self._load_features_nocache(data, image)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 201, in _load_features_nocache
    features_data = data.load_features(image)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/dataset.py", line 319, in load_features
    return features.FeaturesData.from_file(f, self.config)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/features.py", line 142, in from_file
    return getattr(cls, "_from_file_v%d" % version)(s, config)
  File "/code/SuperBuild/install/bin/opensfm/opensfm/features.py", line 253, in _from_file_v3
    descriptors = data["descriptors"]
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/npyio.py", line 245, in __getitem__
    return format.read_array(bytes,
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/format.py", line 777, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/format.py", line 906, in _read_bytes
    r = fp.read(size - len(data))
  File "/usr/lib/python3.9/zipfile.py", line 922, in read
    data = self._read1(n)
  File "/usr/lib/python3.9/zipfile.py", line 998, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```
</details>

I used `pdb` to track down the corrupted file. 

Is there a way to regenerate this precise file ?

Thank you in advance for your time and help! 🚀

**Comment by fabianschenk** [comment]
Hi @Adrien-ANTON-LUDWIG ,

I'd suggest to just rerun everything. One thing you could try is to run the feature extraction again. I have never looked at the ODM project and can't give you any advice how to do it there.

Best,
Fabian

**Comment by Adrien-ANTON-LUDWIG** [comment]
Hi @fabianschenk,

Thanks for the quick response! 

It took me about 5 days to arrive to the `compute_statistics` step.
I'm trying to find the most efficient way to avoid going through it all again.

Will running `detect_features` skip the already computed images?
I mean, could I simply delete the corrupted file, rerun `detect_features` and have it detect only the missing file?

Thank you for your help, much appreciated!

**Comment by fabianschenk** [comment]
Hi @Adrien-ANTON-LUDWIG,

Let's say it should but don't take this as a guarantee. I haven't used OpenSfM in ~1,5 years. Can you back up the already computed features, then delete the corrupted and run `detect_features`?

**Comment by Adrien-ANTON-LUDWIG** [comment]
Okay, thanks!
Yes, I will back up the features. Better safe than sorry.
I will try `detect_features` and let you know about the result.
