### ISSUE TITLE
Error when running `opensfm create_rig`

### ISSUE THREAD

**Issue by ymei** [mapillary/OpenSfM#1012]
I have 4 cameras in a rig with camera names `Left-left`, `Left-right`, `Right-left`, and `Right-right`.  The images files are named `Left-left-001.png` ...  The `camera:` field `exif_overrides.json` is set correctly to each corresponding camera name.  Normal reconstruction without considering rig runs correctly.

However, when I run `opensfm create_rig data camera '{"RIG_CAMERA_ID1": "Left-left", "RIG_CAMERA_ID2": "Left-right", "RIG_CAMERA_ID3": "Right-left", "RIG_CAMERA_ID4": "Right-right"}'`, it shows the following info and error:

```
2023-08-11 10:47:24,678 INFO: Found 4 shots for instance -79.png using pattern matching.
2023-08-11 10:47:24,678 INFO: Found 4 shots for instance -33.png using pattern matching.
2023-08-11 10:47:24,678 INFO: Found 4 shots for instance -228.png using pattern matching.
2023-08-11 10:47:24,678 INFO: Found 4 shots for instance -58.png using pattern matching.
2023-08-11 10:47:24,678 INFO: Found 4 shots for instance -204.png using pattern matching.
2023-08-11 10:47:24,678 INFO: Found 4 shots for instance -96.png using pattern matching.
2023-08-11 10:47:24,678 INFO: Found 0 single shots using pattern matching.
2023-08-11 10:47:25,390 INFO: Found 2 connected components
2023-08-11 10:47:25,394 INFO: Best component has 247 instances
Traceback (most recent call last):
  File "/home/meson/Applications/src/OpenSfM/bin/opensfm_main.py", line 25, in <module>
    commands.command_runner(
  File "/home/meson/Applications/src/OpenSfM/opensfm/commands/command_runner.py", line 38, in command_runner
    command.run(data, args)
  File "/home/meson/Applications/src/OpenSfM/opensfm/commands/command.py", line 13, in run
    self.run_impl(data, args)
  File "/home/meson/Applications/src/OpenSfM/opensfm/commands/create_rig.py", line 15, in run_impl
    create_rig.run_dataset(dataset, args.method, json.loads(args.definition), True)
  File "/home/meson/Applications/src/OpenSfM/opensfm/actions/create_rig.py", line 26, in run_dataset
    rig.create_rigs_with_pattern(data, definition)
  File "/home/meson/Applications/src/OpenSfM/opensfm/rig.py", line 317, in create_rigs_with_pattern
    for subset_data, instances in propose_subset_dataset_from_instances(
  File "/home/meson/Applications/src/OpenSfM/opensfm/rig.py", line 205, in propose_subset_dataset_from_instances
    yield data.subset(name, subset_images), total_instances
  File "/home/meson/Applications/src/OpenSfM/opensfm/dataset.py", line 655, in subset
    subset_dataset = DataSet(subset_dataset_path, self.io_handler)
  File "/home/meson/Applications/src/OpenSfM/opensfm/dataset.py", line 52, in __init__
    self.load_image_list()
  File "/home/meson/Applications/src/OpenSfM/opensfm/dataset.py", line 82, in load_image_list
    raise IOError("No Images found in {}".format(image_list_path))
OSError: No Images found in data/rig_calibration/images
```
I could copy all images to `data/rig_calibration/images` first, make `rig.py` not to delete them then run again.  But then it appears to be reconstructing all the images rather than a select subset of them.  Is this a bug all perhaps I am not using this feature correctly?

**Comment by fabianschenk** [comment]
Hi @adamjson64,
The error seems pretty clear,  your 12-bit TIFF images are not supported.

**Comment by hackgyh** [comment]
Inserting this code in line 655 of dataset. py can solve this problem，maybe
```python
        folders = ["images", "segmentations", "masks"]
        for folder in folders:
            self.io_handler.mkdir_p(os.path.join(subset_dataset_path, folder))

        for img_name in images_subset:
            import shutil
            shutil.copyfile(
                os.path.join(self.data_path, "images", img_name),
                os.path.join(subset_dataset_path, "images", img_name)
                )

        subset_dataset = DataSet(subset_dataset_path, self.io_handler)
```
