### ISSUE TITLE
Error when building using wsl ubuntu

### ISSUE THREAD

**Issue by justin1230** [mapillary/OpenSfM#1040]
[ 38%] Linking CXX static library libakaze.a
[ 38%] Built target akaze
[ 39%] Linking CXX static library libgtest.a
[ 39%] Built target gtest
make: *** [Makefile:101: all] Error 2
Traceback (most recent call last):
  File "/mnt/v/ProjectInstall/ubuntu/OpenSfM/setup.py", line 60, in <module>
    build_c_extension()
  File "/mnt/v/ProjectInstall/ubuntu/OpenSfM/setup.py", line 54, in build_c_extension
    subprocess.check_call(
  File "/home/justin1230/miniconda3/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j32']' returned non-zero exit status 2.

got this error and stopped there.....

I did tried update all , delete the folder and try cloning again.

**Comment by heliguy-sam** [comment]
As recommended in some previous issues, downgrading to ceres-solver-2.0.0 managed to resolve this issue for me.
