### ISSUE TITLE
Getting requirements to build wheel error

### ISSUE THREAD

**Issue by Joeljensen28** [mapillary/OpenSfM#1067]
When trying to run `pip install -r requirements.txt` I get the following error when it hits `pyyaml==5.4`:

```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
...
File "<string>", line 201, in get_source_files
        File "/private/var/folders/y4/920089fs5m9gj38b209z6n4h0000gn/T/pip-build-env-yn0zievh/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I previously ran into this issue and was able to fix as mentioned in the comments of #1022, but I later ran into some new issues, causing me reinstall the repo, and now I'm getting this error whether I have `pyyaml` set to `5.3.1` or `5.4`. My python version is `3.8.19`. What is the cause of this?

**Comment by KuchikiRukia7** [comment]
I also get this error.
How do you solve it?
Thank you.
