### ISSUE TITLE
Error with pip on Windows

### ISSUE THREAD

**Issue by KuchikiRukia7** [mapillary/OpenSfM#1076]
When I pip install,I meet this situation.

E:\OpenSfM>pip install -r requirements.txt
Ignoring opencv-python: markers 'sys_platform == "linux"' don't match your environment
Collecting cloudpickle==0.4.0 (from -r requirements.txt (line 1))
  Using cached cloudpickle-0.4.0-py2.py3-none-any.whl.metadata (3.7 kB)
Collecting exifread==2.1.2 (from -r requirements.txt (line 2))
  Using cached ExifRead-2.1.2.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting flask==2.3.2 (from -r requirements.txt (line 3))
  Using cached Flask-2.3.2-py3-none-any.whl.metadata (3.7 kB)
Collecting fpdf2==2.4.6 (from -r requirements.txt (line 4))
  Using cached fpdf2-2.4.6-py2.py3-none-any.whl.metadata (23 kB)
Collecting joblib==0.14.1 (from -r requirements.txt (line 5))
  Using cached joblib-0.14.1-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting matplotlib (from -r requirements.txt (line 6))
  Using cached matplotlib-3.9.2-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting networkx==2.5 (from -r requirements.txt (line 7))
  Using cached networkx-2.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: numpy>=1.19 in d:\python\lib\site-packages (from -r requirements.txt (line 8)) (2.1.2)
Collecting Pillow>=8.1.1 (from -r requirements.txt (line 9))
  Using cached pillow-11.0.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyproj>=1.9.5.1 (from -r requirements.txt (line 10))
  Using cached pyproj-3.7.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Collecting pytest==3.0.7 (from -r requirements.txt (line 11))
  Using cached pytest-3.0.7-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting python-dateutil>=2.7 (from -r requirements.txt (line 12))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pyyaml==5.4 (from -r requirements.txt (line 13))
  Using cached PyYAML-5.4.tar.gz (174 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "D:\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "D:\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 271, in <module>
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\dist.py", line 991, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 315, in run
          self.find_sources()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 323, in find_sources
          mm.run()
          ~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 544, in run
          self.add_defaults()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 582, in add_defaults
          sdist.add_defaults(self)
          ~~~~~~~~~~~~~~~~~~^^^^^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\command\sdist.py", line 108, in add_defaults
          super().add_defaults()
          ~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
          ~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\1\AppData\Local\Temp\pip-build-env-yp3_o472\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


May I ask what I should do?

**Comment by alessandro-pistola-me** [comment]
Same issue in Ubuntu 22.04.4 LTS

**Comment by HardOldGrit** [comment]
Hi! were you able to resolve this issue? I have the same issue ...

**Comment by KuchikiRukia7** [comment]
Hi!I am using Linux on ubuntu now.I fail to find the solution.And I also have a new issue on Linux.....



---Original---
From: ***@***.***&gt;
Date: Thu, Feb 27, 2025 17:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mapillary/OpenSfM] Error with pip on Windows (Issue #1076)


   
Hi! were you able to resolve this issue? I have the same issue ...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  HardOldGrit left a comment (mapillary/OpenSfM#1076)
 
Hi! were you able to resolve this issue? I have the same issue ...

**Comment by vgutierrez2404** [comment]
What'a your new is sur?

**Comment by vgutierrez2404** [comment]
I use Ubuntu 22.04. As far as I remember, I wasn't able to install the requirements from requirements.txt with PyYAML==5.4. So, I removed it from requirements.txt and installed PyYAML==6.0.1 instead. Try installing it and let me know if it works for you now.
