### ISSUE TITLE
scipy missing from requirements.txt

### ISSUE THREAD

**Issue by samiujan** [mapillary/OpenSfM#155]
I am installing on MacOSX 10.12.3

I created a virtualenv environment and installed all dependencies - however, running the project gives me:

```
(venv) someuser $ bin/run_all data/berlin/
Traceback (most recent call last):
  File "/Users/someuser/code/mapillary/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/Users/someuser/code/mapillary/OpenSfM/opensfm/commands/__init__.py", line 7, in <module>
    import mesh
  File "/Users/someuser/code/mapillary/OpenSfM/opensfm/commands/mesh.py", line 5, in <module>
    from opensfm import mesh
  File "/Users/user/someuser/mapillary/OpenSfM/opensfm/mesh.py", line 4, in <module>
    import scipy.spatial
ImportError: No module named scipy.spatial
```

I fixed it by adding **scipy** to requirements.txt

Does it make sense to create a pull-request for this?

**Comment by paulinus** [comment]
It is missing, indeed. Thanks for pointing out. No need for a PR, i will add it.
