### ISSUE TITLE
ubuntu 16.04 libglog.so Import Error.

### ISSUE THREAD

**Issue by happyfrank** [mapillary/OpenSfM#168]
```
ubuntu@4DAGE:~/OpenSfM$ ./bin/run_all ./data/berlin/
Traceback (most recent call last):
  File "/home/ubuntu/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/ubuntu/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
  File "/home/ubuntu/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/ubuntu/OpenSfM/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/home/ubuntu/OpenSfM/opensfm/io.py", line 10, in <module>
    from opensfm import features
  File "/home/ubuntu/OpenSfM/opensfm/features.py", line 7, in <module>
    import csfm
ImportError: /usr/local/lib/libglog.so.0: undefined symbol: _ZN6google14FlagRegistererC1IiEEPKcS3_S3_PT_S5_
```
I don't have this error when I copy a libglog.so.0 from ubuntu 14.04.

Then I get this error.

```
ubuntu@4DAGE:~/OpenSfM$ ./bin/run_all ./data/lund/
Traceback (most recent call last):
  File "/home/ubuntu/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/ubuntu/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
  File "/home/ubuntu/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/ubuntu/OpenSfM/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/home/ubuntu/OpenSfM/opensfm/io.py", line 10, in <module>
    from opensfm import features
  File "/home/ubuntu/OpenSfM/opensfm/features.py", line 7, in <module>
    import csfm
ImportError: /home/ubuntu/OpenSfM/opensfm/csfm.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

**Comment by paulinus** [comment]
@happyfrank did you solved the issue?

**Comment by happyfrank** [comment]
No, I just change the ubuntu system to 14.04, this problem disappear.

**Comment by nlpguyz** [comment]
I ran into the same problem on Ubuntu 14.04

**Comment by shinfang** [comment]
@nlpguyz did you manage to solve the issue?
