### ISSUE TITLE
ZeroDivisionError when 'GPS GPSAltitude' is Zero

### ISSUE THREAD

**Issue by jleistner** [mapillary/OpenSfM#182]
Hi there,

I found that some images (especially ones that were taken with a Nikon Coolpix AW100) can cause a ZeroDivisonError like below:

```
2017-06-04 12:58:04,256 Extracting focal lengths for image 65.jpg
Traceback (most recent call last):
  File "/path/to/OpenSfM-master/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/path/to/OpenSfM-master/opensfm/commands/extract_metadata.py", line 29, in run
    d = exif.extract_exif_from_file(data.load_image(image))
  File "/path/to/OpenSfM-master/opensfm/exif.py", line 90, in extract_exif_from_file
    d = exif_data.extract_exif()
  File "/path/to/OpenSfM-master/opensfm/exif.py", line 257, in extract_exif
    geo = self.extract_geo()
  File "/path/to/OpenSfM-master/opensfm/exif.py", line 221, in extract_geo
    altitude = self.extract_altitude()
  File "/path/to/OpenSfM-master/opensfm/exif.py", line 208, in extract_altitude
    altitude = eval_frac(self.tags['GPS GPSAltitude'].values[0])
  File "/path/to/OpenSfM-master/opensfm/exif.py", line 18, in eval_frac
    return float(value.num) / float(value.den)
ZeroDivisionError: float division by zero
```
Changing
```python
def eval_frac(value):
    return float(value.num) / float(value.den)
```
to 
```python
def eval_frac(value):
    try:
        return float(value.num) / float(value.den)
    except ZeroDivisionError:
        return 0    # returning zero instead of None to avoid a TypeError
```
fixed the problem for me at least. Maybe you could add a similiar fix to the master branch.

**Comment by paulinus** [comment]
Thanks for the fix. I've set it to return None, since most of the functions in that file use None for missing values.
