### ISSUE TITLE
Matching fails if at least one image has no GPS data

### ISSUE THREAD

**Issue by jleistner** [mapillary/OpenSfM#198]
I've installed the latest version of OpenSfM today and now all my data sets don't work anymore. From the console output below you can see that the matching fails but I can't figure out why.
[townhall.zip](https://github.com/mapillary/OpenSfM/files/1133744/townhall.zip)
```
bin/opensfm_run_all data/townhall
2017-07-09 14:36:09,696 Extracting focal lengths for image IMGP3419.jpg
2017-07-09 14:36:09,700 Extracting focal lengths for image IMGP3428.jpg
2017-07-09 14:36:09,702 Extracting focal lengths for image IMGP3420.jpg
2017-07-09 14:36:09,704 Extracting focal lengths for image IMGP3417.jpg
2017-07-09 14:36:09,706 Extracting focal lengths for image IMGP3425.jpg
2017-07-09 14:36:10,079 Extracting ROOT_HAHOG features for image IMGP3419.jpg
2017-07-09 14:36:10,079 Extracting ROOT_HAHOG features for image IMGP3428.jpg
2017-07-09 14:36:10,079 Extracting ROOT_HAHOG features for image IMGP3420.jpg
2017-07-09 14:36:10,080 Extracting ROOT_HAHOG features for image IMGP3417.jpg
2017-07-09 14:36:10,080 Extracting ROOT_HAHOG features for image IMGP3425.jpg
2017-07-09 14:36:11,178 Found 4827 points in 0.954954862595s
2017-07-09 14:36:11,183 Found 4889 points in 1.01493597031s
2017-07-09 14:36:11,407 Found 4888 points in 1.18394899368s
2017-07-09 14:36:11,476 Found 4885 points in 1.27148008347s
2017-07-09 14:36:11,774 Found 4809 points in 1.55314683914s
2017-07-09 14:36:12,325 Matching 0 image pairs
2017-07-09 14:36:12,350 Matching IMGP3428.jpg  -  1 / 5
2017-07-09 14:36:12,350 Matching IMGP3425.jpg  -  2 / 5
2017-07-09 14:36:12,351 Matching IMGP3419.jpg  -  3 / 5
2017-07-09 14:36:12,351 Matching IMGP3417.jpg  -  4 / 5
2017-07-09 14:36:12,351 Matching IMGP3420.jpg  -  5 / 5
2017-07-09 14:36:12,794 reading features
2017-07-09 14:36:12,881 Merging features onto tracks
2017-07-09 14:36:12,881 Good tracks: 0
2017-07-09 14:36:13,212 Starting incremental reconstruction
2017-07-09 14:36:13,238 0 partial reconstructions in total.
Traceback (most recent call last):
  File "OpenSfM-master/bin/opensfm", line 34, in <module>
    command.run(args)
  File "OpenSfM-master/opensfm/commands/mesh.py", line 22, in run
    reconstructions = data.load_reconstruction()
  File "OpenSfM-master/opensfm/dataset.py", line 355, in load_reconstruction
    with open(self.__reconstruction_file(filename)) as fin:
IOError: [Errno 2] No such file or directory: 'data/townhall/reconstruction.json'
```
Both example data sets work fine. An older version of OpenSfM on a different machine does work fine as well. I've already tried the following:

- reinstall OpenSfM (multiple times)
- use the default config
- use SIFT instead of HAHOG
- use a different data set (multiple)

What am I missing?

**Comment by jleistner** [comment]
After some more investigating I think I found the source of the problem.
In 9daf5e1ea92ed785e07f3e83d277b61eaa072877 [match_features](https://github.com/mapillary/OpenSfM/blob/master/opensfm/commands/match_features.py) was changed. Since I have a lot of images without GPS data ```matching_gps_neighbors``` gets disabled and ```max_distance``` is set to ```0```. This results in the error described above because now all match_candidates-functions return an empty set and therefore there are no image pairs at all.  
If I don't set ```max_distance``` to ```0``` and instead leave it at it's default value of ```150``` (remove line 162 in [match_features.py](https://github.com/mapillary/OpenSfM/blob/master/opensfm/commands/match_features.py)) I get a ```KeyError```:
```
Traceback (most recent call last):
  File "OpenSfM-0.1.0/bin/opensfm", line 34, in <module>
    command.run(args)
  File "OpenSfM-0.1.0/opensfm/commands/match_features.py", line 26, in run
    pairs = match_candidates_from_metadata(images, exifs, data)
  File "OpenSfM-0.1.0/opensfm/commands/match_features.py", line 185, in match_candidates_from_metadata
    gps_neighbors, max_distance)
  File "OpenSfM-0.1.0/opensfm/commands/match_features.py", line 94, in match_candidates_by_distance
    gps['latitude'], gps['longitude'], gps['altitude'],
KeyError: 'latitude'
```
Which is not surprising because ```gps``` is now empty but easily fixed by changing 
```python
points[i] = geo.topocentric_from_lla(
            gps['latitude'], gps['longitude'], gps['altitude'],
            reference['latitude'], reference['longitude'], reference['altitude'])
```
to
```python
try:
     points[i] = geo.topocentric_from_lla(
           gps['latitude'], gps['longitude'], gps['altitude'],
           reference['latitude'], reference['longitude'], reference['altitude'])
except KeyError:
     points[i] = geo.topocentric_from_lla(
           0, 0, 0,
           reference['latitude'], reference['longitude'], reference['altitude'])
```
It's not a great solution but it fixes the problem.
Maybe somebody has a better idea how to handle missing GPS data.

**Comment by gsig** [comment]
Same problem here. The demos worked out of the box without any problems. But, when applying it to my own images (images extract from videos using ffmpeg) no amount of tuning (features, parameters, etc) resulted in any matches/good tracks/partial reconstructions.

This fix worked for me. Thanks!

**Comment by YanNoun** [comment]
@jleistner @gsig this has been fixed a while and is handled at this line : https://github.com/mapillary/OpenSfM/blame/master/opensfm/pairs_selection.py#L354
