### ISSUE TITLE
No good tracks from dataset

### ISSUE THREAD

**Issue by sola92** [mapillary/OpenSfM#201]
When I run `opensfm_run_all` on my dataset. It isn't able to find any good tracks. I'm not quite sure what is wrong here. 

Dataset: [https://drive.google.com/open?id=0BztPTt1YkSzRMUtkZVZxSVhUejg](https://drive.google.com/open?id=0BztPTt1YkSzRMUtkZVZxSVhUejg)

Here is the log output:

```2017-07-17 22:03:47,734 Extracting focal lengths for image DSC_0057.JPG
2017-07-17 22:03:47,749 Extracting focal lengths for image DSC_0058.JPG
2017-07-17 22:03:47,766 Extracting focal lengths for image DSC_0059.JPG
2017-07-17 22:03:47,777 Extracting focal lengths for image DSC_0060.JPG
2017-07-17 22:03:47,791 Extracting focal lengths for image DSC_0061.JPG
2017-07-17 22:03:47,802 Extracting focal lengths for image DSC_0062.JPG
2017-07-17 22:03:47,821 Extracting focal lengths for image DSC_0063.JPG
2017-07-17 22:03:47,833 Extracting focal lengths for image DSC_0064.JPG
2017-07-17 22:03:47,853 Extracting focal lengths for image DSC_0065.JPG
2017-07-17 22:03:48,449 Extracting ROOT_HAHOG features for image DSC_0058.JPG
2017-07-17 22:03:48,449 Extracting ROOT_HAHOG features for image DSC_0057.JPG
2017-07-17 22:03:48,450 Extracting ROOT_HAHOG features for image DSC_0059.JPG
2017-07-17 22:03:48,450 Extracting ROOT_HAHOG features for image DSC_0060.JPG
2017-07-17 22:03:48,451 Extracting ROOT_HAHOG features for image DSC_0061.JPG
2017-07-17 22:03:48,451 Extracting ROOT_HAHOG features for image DSC_0062.JPG
2017-07-17 22:03:48,452 Extracting ROOT_HAHOG features for image DSC_0065.JPG
2017-07-17 22:03:48,451 Extracting ROOT_HAHOG features for image DSC_0063.JPG
2017-07-17 22:03:48,452 Extracting ROOT_HAHOG features for image DSC_0064.JPG
2017-07-17 22:03:49,012 Matching 0 image pairs
2017-07-17 22:03:49,030 Matching DSC_0059.JPG  -  1 / 9
2017-07-17 22:03:49,031 Matching DSC_0064.JPG  -  2 / 9
2017-07-17 22:03:49,032 Matching DSC_0060.JPG  -  3 / 9
2017-07-17 22:03:49,033 Matching DSC_0058.JPG  -  4 / 9
2017-07-17 22:03:49,034 Matching DSC_0057.JPG  -  5 / 9
2017-07-17 22:03:49,035 Matching DSC_0062.JPG  -  6 / 9
2017-07-17 22:03:49,036 Matching DSC_0061.JPG  -  7 / 9
2017-07-17 22:03:49,038 Matching DSC_0065.JPG  -  9 / 9
2017-07-17 22:03:49,037 Matching DSC_0063.JPG  -  8 / 9
2017-07-17 22:03:49,667 reading features
2017-07-17 22:03:49,866 Merging features onto tracks
2017-07-17 22:03:49,866 Good tracks: 0
2017-07-17 22:03:50,338 Starting incremental reconstruction
2017-07-17 22:03:50,351 0 partial reconstructions in total.
Traceback (most recent call last):
  File ".../opengv/build/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File ".../opengv/build/OpenSfM/opensfm/commands/mesh.py", line 22, in run
    reconstructions = data.load_reconstruction()
  File ".../opengv/build/OpenSfM/opensfm/dataset.py", line 356, in load_reconstruction
    reconstructions = io.reconstructions_from_json(json.load(fin))
  File "~/.pyenv/versions/2.7.3/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "~/.pyenv/versions/2.7.3/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "~/.pyenv/versions/2.7.3/lib/python2.7/json/decoder.py", line 366, in decode```

**Comment by erikreed** [comment]
Maybe no GPS data in your images?

Try adding
```yml
matching_order_neighbors: 10
```
to your config.yaml.

**Comment by sola92** [comment]
Works great. Thanks!
