### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'data/berlin/camera_models.json'

### ISSUE THREAD

**Issue by equinoxyz** [mapillary/OpenSfM#205]
Hello I built the "python setup.py build“ without problems but when I run "bin/opensfm_run_all data/berlin" I get the following error:
File "/home/zyx/Downloads/OpenSfM-master/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/zyx/Downloads/OpenSfM-master/opensfm/commands/extract_metadata.py", line 53, in run
    data.save_camera_models(camera_models)
  File "/home/zyx/Downloads/OpenSfM-master/opensfm/dataset.py", line 420, in save_camera_models
    with open(self.__camera_models_file(), 'w') as fout:
IOError: [Errno 2] No such file or directory: 'data/berlin/camera_models.json'
Would anyone be able  to help?

**Comment by paulinus** [comment]
This looks like there was a problem trying to create a file on the system. The line that is failing is trying to create a file. Can't see why it would complain about the file missing. Are you using any special drive, maybe write-only?

**Comment by hblanken** [comment]
My berlin dataset runs very well with docker. However, I have the same issue with lund.

docker run -ti mapillary/opensfm /bin/sh -c "bin/opensfm_run_all data/lund"
Traceback (most recent call last):
  File "/source/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/source/OpenSfM/opensfm/commands/extract_metadata.py", line 56, in run
    data.save_camera_models(camera_models)
  File "/source/OpenSfM/opensfm/dataset.py", line 438, in save_camera_models
    with io.open_wt(self.__camera_models_file()) as fout:
  File "/source/OpenSfM/opensfm/io.py", line 445, in open_wt
    return io.open(path, 'w', encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'data/lund/camera_models.json'

Can it not find the correct exif data in these examples?

**Comment by YanNoun** [comment]
Solution found by @hblanken , closing.
