### ISSUE TITLE
fail install opengv

### ISSUE THREAD

**Issue by De-Lac** [mapillary/OpenSfM#212]
According to the Readme, when I do

```
cmake .. -DBUILD_TESTS=OFF -DBUILD_PYTHON=ON
make install
```

I got this error

```
Scanning dependencies of target pyopengv
[ 98%] Building CXX object python/CMakeFiles/pyopengv.dir/pyopengv.o
In file included from ~/OpenSfM/opengv/python/pyopengv.cpp:14:
~/OpenSfM/opengv/python/types.hpp:14:17: error: no namespace named 'numeric' in
      namespace 'boost::python'; did you mean 'boost::numeric'?
namespace bpn = boost::python::numeric;
                ^~~~~~~~~~~~~~~~~~~~~~
                boost::numeric
```

I am on MacOSX Sierra 10.12.6, Python 2.7.10

**Comment by De-Lac** [comment]
this is the complete error list

```
[ 98%] Building CXX object python/CMakeFiles/pyopengv.dir/pyopengv.cpp.o
In file included from /Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:9:
In file included from /Users/danielefani/OpenSfM/opengv/include/opengv/sac_problems/absolute_pose/AbsolutePoseSacProblem.hpp:42:
In file included from /Users/danielefani/OpenSfM/opengv/include/opengv/sac/SampleConsensusProblem.hpp:237:
/Users/danielefani/OpenSfM/opengv/include/opengv/sac/implementation/SampleConsensusProblem.hpp:45:48: error: 
      no member named 'bind' in namespace 'std'; did you mean 'find'?
  rng_gen_.reset(new std::function<int()>(std::bind(*rng_dist_, rng_alg_)));
                                          ~~~~~^~~~
                                               find
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:862:1: note: 
      'find' declared here
find(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
In file included from /Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:14:
/Users/danielefani/OpenSfM/opengv/python/types.hpp:14:17: error: no namespace named 'numeric' in
      namespace 'boost::python'; did you mean 'boost::numeric'?
namespace bpn = boost::python::numeric;
                ^~~~~~~~~~~~~~~~~~~~~~
                boost::numeric
/usr/local/include/boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_long_long.hpp:9:29: note: 
      namespace 'boost::numeric' defined here
namespace boost { namespace numeric {
                            ^
In file included from /Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:14:
/Users/danielefani/OpenSfM/opengv/python/types.hpp:47:15: error: no member named 'array' in
      namespace 'boost::numeric'
  return bpn::array(handle).copy(); // copy the object. numpy owns the copy now.
         ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/types.hpp:60:30: error: no type named 'array' in namespace
      'boost::numeric'
  PyArrayContiguousView(bpn::array &array) {
                        ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:35:17: error: no namespace named 'numeric' in
      namespace 'boost::python'; did you mean 'boost::numeric'?
namespace bpn = boost::python::numeric;
                ^~~~~~~~~~~~~~~~~~~~~~
                boost::numeric
/usr/local/include/boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_long_long.hpp:9:29: note: 
      namespace 'boost::numeric' defined here
namespace boost { namespace numeric {
                            ^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:149:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & bearingVectors,
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:150:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & points )
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:156:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & bearingVectors,
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:157:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & points,
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:158:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & R )
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:171:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & bearingVectors,
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:172:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & points,
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:173:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & t,
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:174:12: error: no type named 'array' in
      namespace 'boost::numeric'
      bpn::array & R )
      ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:225:22: error: no type named 'array' in
      namespace 'boost::numeric'
bp::object p2p( bpn::array &v, bpn::array &p, bpn::array &R )
                ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:225:37: error: no type named 'array' in
      namespace 'boost::numeric'
bp::object p2p( bpn::array &v, bpn::array &p, bpn::array &R )
                               ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:225:52: error: no type named 'array' in
      namespace 'boost::numeric'
bp::object p2p( bpn::array &v, bpn::array &p, bpn::array &R )
                                              ~~~~~^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:229:5: error: no matching function for call to
      'p2p'
    opengv::absolute_pose::p2p(adapter, 0, 1));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/danielefani/OpenSfM/opengv/include/opengv/absolute_pose/methods.hpp:86:15: note: candidate
      function not viable: no known conversion from
      'pyopengv::absolute_pose::CentralAbsoluteAdapter' to 'const
      opengv::absolute_pose::AbsoluteAdapterBase' for 1st argument
translation_t p2p(
              ^
/Users/danielefani/OpenSfM/opengv/include/opengv/absolute_pose/methods.hpp:68:15: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
translation_t p2p(
              ^
/Users/danielefani/OpenSfM/opengv/python/pyopengv.cpp:232:28: error: no type named 'array' in
      namespace 'boost::numeric'
bp::object p3p_kneip( bpn::array &v, bpn::array &p )
                      ~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by henriquesobral** [comment]
I had to use 1.64 version of boost and boost-python.

**Comment by De-Lac** [comment]
@henriquesobral  Do you have a link where I can find that version? I really can't find it.
Thanks

**Comment by henriquesobral** [comment]
If you're using brew to install them, you will have to edit both formulas files.

Use ```brew edit boost``` to edit boost's formula and replace it using the content of this file https://raw.githubusercontent.com/Homebrew/homebrew-core/3df9cdfc25f796ec8d3ffd0a0a12476cf6d413d5/Formula/boost.rb

then ```brew edit boost-python``` to edit boost-python's formula and replace it using the content of this file https://raw.githubusercontent.com/Homebrew/homebrew-core/d22f78c56a1c7d8e711a407c2dae5fc42f4ae6c2/Formula/boost-python.rb

After that install boost and boost-python using brew ```brew install boost boost-python```

If you're not using brew, these are the links to download source code.
Boost: https://github.com/boostorg/boost/releases
Boost-Python: https://github.com/boostorg/python/releases

**Comment by De-Lac** [comment]
great! now it build without any error.
But when I run 
`bin/opensfm_run_all data/berlin/`

I've got : `No module named cv2`

even if I've installed opencv and opengv :(

```
Traceback (most recent call last):
  File "/Users/danielefani/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/Users/danielefani/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
  File "/Users/danielefani/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/Users/danielefani/OpenSfM/opensfm/dataset.py", line 10, in <module>
    import cv2
ImportError: No module named cv2
```

**Comment by De-Lac** [comment]
thank you. Now everything works!
Actually, the 3D models are quite chaotic, maybe some parameter is wrong.
Anyway it works! thank you again

**Comment by pedroscaff** [comment]
I had the same issue on my MacOS but this didn't work, I used `brew rm` to remove `boost` and `boost-python`, edited the formulas and installed again. the same issue happened, am I missing any step? thanks!

**Comment by paulinus** [comment]
opengv and OpenSfM have problems with the latest boost version. Can you try installing an older one with
`brew switch boost 1.62.0`

**Comment by pedroscaff** [comment]
thanks for the quick reply! this version is not listed on brew, I tried with `boost@1.59` + `boost-python@1.59` but the compilation also didn't work (and here I apologize if I am being slow because I never had to do this with homebrew). I am avoiding installing boost from the source, do you think there is another solution?

**Comment by jololhuet** [comment]
`boost@1.58` is working fine for me with python 3.6 but had to change some lines of the `CMakeLists` or set the libboost to use `python-py35` because the `libboost_python-py36` does not exist for me..

**Comment by paulinus** [comment]
@pedroscaff, after some work, both opensfm and opengv (in the [paulinus/opengv](https://github.com/paulinus/opengv) fork) support recent versions of Boost and Python 3.

@jololhuet, can you share the changes you needed to do in `CMakeLists`?

Closing this since the original issue is solved.
