### ISSUE TITLE
when use python setup.py, I encounter the following problem. I don't know why

### ISSUE THREAD

**Issue by AlphaSunny** [mapillary/OpenSfM#247]
Configuring...
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    subprocess.Popen(['cmake','../opensfm/src'], cwd='cmake_build').wait()
  File "D:\Anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\Anaconda2\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by paulinus** [comment]
Looks like it is having problems running cmake. Is cmake installed on your system?

**Comment by AlphaSunny** [comment]
Thanks a lot for your reply, I think i don't have the cmake installed. I will try it. Thanks a lot.
