### ISSUE TITLE
Running 'compute_depthmaps' in parallel

### ISSUE THREAD

**Issue by theriny** [mapillary/OpenSfM#257]
Sometimes when running `compute_depthmaps` with `processes: 8` (on Windows in Docker) in `config.yaml`, the following error occurs:

```
root@41bae1167e2d:/source/OpenSfM# bin/opensfm compute_depthmaps data/mtndew/
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:51,797 INFO: Computing neighbors
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:53,225 INFO: Using precomputed raw depthmap IMG_20171220_162045249.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:53,402 INFO: Using precomputed raw depthmap IMG_20171220_162030199.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:53,574 INFO: Using precomputed raw depthmap IMG_20171220_162122559.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:53,752 INFO: Using precomputed raw depthmap IMG_20171220_162105308.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:53,922 INFO: Using precomputed raw depthmap IMG_20171220_162212177.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:54,096 INFO: Using precomputed raw depthmap IMG_20171220_162208286.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:54,271 INFO: Using precomputed raw depthmap IMG_20171220_162222846.jpg
libdc1394 error: Failed to initialize libdc1394
2017-12-21 20:05:54,441 INFO: Computing depthmap for image IMG_20171220_162237448.jpg with PATCH_MATCH
2017-12-21 20:05:54,442 INFO: Computing depthmap for image IMG_20171220_162150520.jpg with PATCH_MATCH
2017-12-21 20:05:54,442 INFO: Computing depthmap for image IMG_20171220_162232619.jpg with PATCH_MATCH
2017-12-21 20:05:54,442 INFO: Computing depthmap for image IMG_20171220_162023181.jpg with PATCH_MATCH
2017-12-21 20:05:54,442 INFO: Computing depthmap for image IMG_20171220_162055436.jpg with PATCH_MATCH
2017-12-21 20:05:54,443 INFO: Computing depthmap for image IMG_20171220_162228349.jpg with PATCH_MATCH
2017-12-21 20:05:54,464 INFO: Using precomputed raw depthmap IMG_20171220_162205045.jpg
2017-12-21 20:05:54,464 INFO: Computing depthmap for image IMG_20171220_162113903.jpg with PATCH_MATCH
2017-12-21 20:05:54,482 INFO: Computing depthmap for image IMG_20171220_162201316.jpg with PATCH_MATCH
Traceback (most recent call last):
  File "bin/opensfm", line 34, in <module>
    command.run(args)
  File "/source/OpenSfM/opensfm/commands/compute_depthmaps.py", line 25, in run
    dense.compute_depthmaps(data, graph, reconstructions[0])
  File "/source/OpenSfM/opensfm/dense.py", line 35, in compute_depthmaps
    parallel_map(compute_depthmap_catched, arguments, processes)
  File "/source/OpenSfM/opensfm/context.py", line 38, in parallel_map
    return list(e.map(func, args))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 769, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 584, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 382, in __get_result
    raise self._exception
loky.process_executor.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

Re-running `compute_depthmaps` several times may continue past computing depthmaps, but some of the `.npz` archives are corrupted and merging depthmaps fails with BadZipFile errors.

Running with `processes: 1` seems to work around the issue.

**Comment by paulinus** [comment]
It looks like one process dies and then the process is stopped. The corrupted files are likely the consequence of the processes being killed while writing.

I don't know why the first process is dying. Could it be running out of memory?  Could you maybe try with `processes: 2`? That will use less memory while still using a parallel execution. That should tell us if the problem is memory or related to the parallel processing itself.

**Comment by theriny** [comment]
I'll let you know what happens.

**Comment by theriny** [comment]
The codes runs smoothly with  processes: 2

**Comment by paulinus** [comment]
Then my guess is that with more processes it runs out of memory an gets killed.

**Comment by theriny** [comment]
Makes sense

**Comment by PeterSprague** [comment]
Get similar errors:
Never come close to max memory, cpu ramps hard at hog process, then ambles along
On packet.net type-2a2 64 core arm64v8 w/ 128Gb ram
157 images
see: https://github.com/OpenDroneMap/WebODM/issues/314
settings.yaml - opensfm @ default aka nproc
@01:29
...
PATCH_MATCH
2018-01-30 03:18:06,454 Computing depthmap for image 2017_0909_115328_174.JPG with PATCH_MATCH
2018-01-30 03:18:06,883 Computing depthmap for image 2017_0909_115808_310.JPG with PATCH_MATCH
2018-01-30 03:18:07,283 Computing depthmap for image 2017_0909_115639_270.JPG with PATCH_MATCH
Traceback (most recent call last):
  File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/compute_depthmaps.py", line 25, in run
    dense.compute_depthmaps(data, graph, reconstructions[0])
  File "/code/SuperBuild/src/opensfm/opensfm/dense.py", line 35, in compute_depthmaps
    parallel_map(compute_depthmap_catched, arguments, processes)
  File "/code/SuperBuild/src/opensfm/opensfm/context.py", line 20, in parallel_map
    return list(e.map(func, args))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 769, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 584, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 382, in __get_result
    raise self._exception
loky.process_executor.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 138, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

Seen this type of issue too much, thought was related to memory usage but in this case memory  was never close to max.

**Comment by paulinus** [comment]
@PeterSprague, when a subprocess fails for any reason, we get the generic error `A process in the process pool was terminated abruptly while the future was running or pending.`

It would be helpful if you could run with only one process. This way you will see the error of the breaking process instead of the generic one. Thanks!

**Comment by PeterSprague** [comment]
On packet.net type-2a2 32 core arm64v8 w/ 128Gb ram
Node-OpenDroneMap based on OpenDroneMap built for arm64v8 w/ OSMesa & VTK-v8.1.0 source 
157 images
opensfm @ 1
Time Elapsed: 03:27:55
---------------------------------------------
2018-02-06 22:48:13,148 INFO: Computing depthmap for image 2017_0909_115513_226.JPG with PATCH_MATCH
2018-02-06 22:49:05,567 INFO: Computing depthmap for image 2017_0909_115554_246.JPG with PATCH_MATCH
2018-02-06 22:49:55,684 INFO: Computing depthmap for image 2017_0909_115804_308.JPG with PATCH_MATCH
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 154, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by YanNoun** [comment]
@PeterSprague @theriny OpenSfM now use multithreading instead of multiprocessing which is solving many RAM consumption and parallel computation issues.
