### ISSUE TITLE
Mismatched parameters

### ISSUE THREAD

**Issue by dakotabenjamin** [mapillary/OpenSfM#264]
Pulled master today and ran into an error during incremental reconstruction:
```
[DEBUG]   running PYTHONPATH=/home/dmb2/db-odm/SuperBuild/install/lib/python2.7/dist-packages /home/dmb2/db-odm/SuperBuild/src/opensfm/bin/opensfm reconstruct /home/dmb2/ODMProjects/toledo/opensfm
2018-01-10 14:21:03,709 INFO: Starting incremental reconstruction
2018-01-10 14:21:25,876 INFO: Starting reconstruction with DJI_0066.JPG and DJI_0075.JPG
2018-01-10 14:21:26,049 INFO: Two-view reconstruction inliers: 2200 / 2203
2018-01-10 14:21:26,636 INFO: Triangulated: 2202
Traceback (most recent call last):
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/commands/reconstruct.py", line 21, in run
    report = reconstruction.incremental_reconstruction(data)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/reconstruction.py", line 1095, in incremental_reconstruction
    data, graph, im1, im2, p1, p2)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/reconstruction.py", line 669, in bootstrap_reconstruction
    bundle_single_view(graph, reconstruction, im2, data.config)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/reconstruction.py", line 218, in bundle_single_view
    config['radial_distorsion_k3_sd'])
Boost.Python.ArgumentError: Python argument types in
    BundleAdjuster.set_internal_parameters_prior_sd(BundleAdjuster, float, float, float, float, float, float, float)
did not match C++ signature:
    set_internal_parameters_prior_sd(BundleAdjuster {lvalue}, double, double, double)
Traceback (most recent call last):
  File "/home/dmb2/db-odm/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/home/dmb2/db-odm/scripts/run_opensfm.py", line 124, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/home/dmb2/db-odm/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

I have boost v 1.58 installed. It looks like these code changes were implemented in the last month with the Brown camera addition.

**Comment by paulinus** [comment]
The changes have changed the C++ API. Can you try rebuilding by running
```
python setup.py build
```

**Comment by YanNoun** [comment]
No answer for a while, closing.
