### ISSUE TITLE
bug: UnboundLocalError in matching

### ISSUE THREAD

**Issue by dakotabenjamin** [mapillary/OpenSfM#275]
In https://github.com/mapillary/OpenSfM/blob/master/opensfm/commands/match_features.py#L196, local variables `d`, `t`, and `o` aren't set when `max_distance == gps_neighbors == time_neighbors == order_neighbors == 0` is set to true. This can happen if you are trying to use gcps for instance or matching photos with no geocoordinates. 
The full error: 
```
Traceback (most recent call last):
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 30, in run
    pairs, preport = match_candidates_from_metadata(images, exifs, data)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 193, in match_candidates_from_metadata
    "num_pairs_distance": len(d),
UnboundLocalError: local variable 'd' referenced before assignment
```

**Comment by paulinus** [comment]
@dakotabenjamin, this was indeed a bug. It is fixed on current master, by setting the variables to empty sets https://github.com/mapillary/OpenSfM/blob/master/opensfm/commands/match_features.py#L180-L182
