### ISSUE TITLE
Can I use CUDA 9.0?

### ISSUE THREAD

**Issue by ywpkwon** [mapillary/OpenSfM#276]
While I was working with this great open source, I updated CUDA from 8.0 to 9.0, and got an error as below. How can I solve this? How can I update csfm?

````
$ bin/opensfm_run_all data/berlin    
Traceback (most recent call last):
  File "/home/paul/projects/sfm/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/paul/projects/sfm/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
  File "/home/paul/projects/sfm/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/paul/projects/sfm/OpenSfM/opensfm/dataset.py", line 11, in <module>
    from opensfm import io
  File "/home/paul/projects/sfm/OpenSfM/opensfm/io.py", line 10, in <module>
    from opensfm import features
  File "/home/paul/projects/sfm/OpenSfM/opensfm/features.py", line 7, in <module>
    import csfm
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
````

**Comment by ywpkwon** [comment]
Oh, I found out. I re-built OpenCV, and then, openSfM. It works well now.

**Comment by paulinus** [comment]
@hy9be OpenSfM does not use Cuda at all, so no changes are required on its side.

**Comment by hy9be** [comment]
@paulinus Thanks! Just realized it is used by opencv actually.

**Comment by Geo-fortune** [comment]
so, if I complied opencv after i installed cuda9, the problem can solved?

**Comment by paulinus** [comment]
Make sure to recompile OpenSfM after changing anything in opencv and you should be good. Since opensfm does not use any cuda function, it should not matter when or how you build opencv.
