### ISSUE TITLE
Atom CPU producing "illegal instruction" error

### ISSUE THREAD

**Issue by PeterSprague** [mapillary/OpenSfM#277]
See: https://github.com/OpenDroneMap/WebODM/issues/314
I'm also getting a very similar error, running as ODM node.

Docker images work fine on an amd64 workstation w/ 32 cores & 64Gb ram.  

Tuning & testing for lower resource hardware
On packet.net type-0 4 core atom w/ 8Gb ram
docker --limit-mem 7G --> so to leave rm for OS
157 images

settings.yaml - opensfm @ 2
@01:56 of run
2018-01-28 23:52:13,033 Robust matching time : 0.000956058502197s
2018-01-28 23:52:13,033 Full matching 264 / 279, time: 9.20634508133s
2018-01-28 23:52:22,074 2017_0909_115521_230.JPG - 2017_0909_115558_248.JPG has 397 candidate matches
2018-01-28 23:52:22,076 Robust matching time : 0.00139093399048s
2018-01-28 23:52:22,076 Full matching 360 / 397, time: 9.04226994514s
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm create_tracks /var/www/data/0f1e05af-76f5-4cf5-984b-e5a1fef84764/opensfm
2018-01-28 23:52:23,363 reading features
2018-01-28 23:52:43,032 Merging features onto tracks
2018-01-28 23:53:14,937 Good tracks: 169240
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm reconstruct /var/www/data/0f1e05af-76f5-4cf5-984b-e5a1fef84764/opensfm
2018-01-28 23:54:05,452 Starting incremental reconstruction
2018-01-28 23:55:25,230 Starting reconstruction with 2017_0909_114819_028.JPG and 2017_0909_114823_030.JPG
2018-01-28 23:55:25,231 Common tracks: 5438
/usr/local/lib/python2.7/dist-packages/loky/backend/semaphore_tracker.py:170: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Illegal instruction (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 115, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 132

settings.yaml - opensfm @ 1
@03:36 of run
2018-01-29 06:52:00,566 Robust matching time : 0.00222086906433s
2018-01-29 06:52:00,566 Full matching 113 / 133, time: 8.93961906433s
2018-01-29 06:52:09,607 2017_0909_115521_230.JPG - 2017_0909_115532_236.JPG has 282 candidate matches
2018-01-29 06:52:09,608 Robust matching time : 0.000813007354736s
2018-01-29 06:52:09,609 Full matching 272 / 282, time: 9.04200792313s
2018-01-29 06:52:18,582 2017_0909_115521_230.JPG - 2017_0909_115558_248.JPG has 404 candidate matches
2018-01-29 06:52:18,584 Robust matching time : 0.00192189216614s
2018-01-29 06:52:18,584 Full matching 365 / 404, time: 8.9751970768s
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm create_tracks /var/www/data/e3586734-55ee-41b6-adce-a6a9ad815891/opensfm
2018-01-29 06:52:19,683 reading features
2018-01-29 06:52:39,300 Merging features onto tracks
2018-01-29 06:53:11,229 Good tracks: 169237
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm reconstruct /var/www/data/e3586734-55ee-41b6-adce-a6a9ad815891/opensfm
2018-01-29 06:54:02,753 Starting incremental reconstruction
2018-01-29 06:55:33,190 Starting reconstruction with 2017_0909_114819_028.JPG and 2017_0909_114823_030.JPG
2018-01-29 06:55:33,191 Common tracks: 5239
Illegal instruction (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 115, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 132

**Comment by paulinus** [comment]
Are you building the docker image on the same architecture that you are running it?

We have observed a similar issue where we were getting `Illegal instruction`. We trace it down to a random number generation used in opengv. The compiler used a processor instruction that is only available on certain architectures.

The solution was to build opengv for the particular architecture where it was going to be run. See
https://github.com/paulinus/opengv/commit/979f99805c029ffb9d38fc50f846be5e7b17d6f2

**Comment by PeterSprague** [comment]
Just checked with packet support, the Type 0 instance is amd64.  Images were built on a amd64 workstation.

**Comment by paulinus** [comment]
Thanks for trying that. Not sure why it happens then but we have seen this happening before on AWS instances. The only solution we have found is to build opengv with the `-march=core2` option as in https://github.com/paulinus/opengv/commit/979f99805c029ffb9d38fc50f846be5e7b17d6f2

**Comment by PeterSprague** [comment]
Pulled that branch into the ODM build for ARM64V8 builds.  Would there be any problems using that branch with AMD64 builds?

**Comment by paulinus** [comment]
That branch does not have the ARM compilation options, which have not been merged upstream (https://github.com/laurentkneip/opengv/pull/44).

My fork in paulinus/opengv master has those changes and other whose corresponding PR are not yet merged upstream.

I'll add a way to optionally set the `-march=core2` option is in paulinus/opengv master. That way you can use that branch and set the arch parameter at will.

**Comment by PeterSprague** [comment]
Thanks, will give it a spin today.

I was pulling in your fork with march-core2 branch, but this will be more straight forward

**Comment by PeterSprague** [comment]
Going through your code change.  What is the correct usage in cmake?

**Comment by paulinus** [comment]
`cmake .. -DBUILD_ARCH=core2  [other_cmake_options]` should do it.

**Comment by PeterSprague** [comment]
New error:
TypeError: write() argument 1 must be unicode, not str
Is this from not building with core2 flag?

amd64 32 core 64Gb
opensfm_processes @16
w/o core2
no fast_ortho checked
VTK v8.1.0
2018-02-01 21:13:25,053 INFO: 1 partial reconstructions in total.
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm mesh /var/www/data/7b2e570d-cc7b-4c88-aa1f-7d2605d50859/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_visualsfm /var/www/data/7b2e570d-cc7b-4c88-aa1f-7d2605d50859/opensfm
Traceback (most recent call last):
  File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/export_visualsfm.py", line 31, in run
    self.export(reconstructions[0], graph, data)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/export_visualsfm.py", line 49, in export
    fout.write('\n'.join(lines))
TypeError: write() argument 1 must be unicode, not str
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 139, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

**Comment by paulinus** [comment]
My bad, I've introduced a bug today when adding python3 compatibility. I've just fixed it. Can you please retry with current master? Thanks.

**Comment by PeterSprague** [comment]
Will rebuild again.  I had added back in core2 thinking it was that.  Core2 actually works fine with amd64 except for caling fast_orthophoto

**Comment by PeterSprague** [comment]
Will rebuild again.  I had added back in core2 thinking that was it.  Core2 actually works fine with amd64 except when calling fast_orthophoto.  So w/o core2 for amd64?

**Comment by PeterSprague** [comment]
Cloning into 'opengv'...
[ 10%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_lzma.c.o
[ 10%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_lzw.c.o
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 44%] No patch step for 'opengv'
[ 45%] No update step for 'opengv'
[ 45%] Performing configure step for 'opengv'
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_next.c.o
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_ojpeg.c.o
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_open.c.o
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_packbits.c.o
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_pixarlog.c.o
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_predict.c.o
-- Detecting CXX compile features - done
-- Found Eigen: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   python
Not using boost/python/numpy.
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython2.7.so (found version "2.7.13") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.13") 
-- Found NumPy: version "1.12.1" /usr/lib/python2.7/dist-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to: /code/SuperBuild/build/opengv
[ 46%] Performing build step for 'opengv'
[ 11%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_print.c.o
[ 12%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_read.c.o
Scanning dependencies of target opengv
[  1%] Building CXX object CMakeFiles/opengv.dir/src/absolute_pose/modules/main.cpp.o
/code/SuperBuild/src/opengv/src/absolute_pose/modules/main.cpp:1:0: error: unknown value 'core2' for -march

**Comment by PeterSprague** [comment]
On Jetson TX-2 6 core arm64v8 w/ 8Gb ram
Node-OpenDroneMap based on OpenDroneMap rebuilt for arm64v8 w/ OSMesa & VTK-v8.1.0 source
Based on GCC doc, explicitly set -march=native for VTK build
amd64 version builds and processes images w/o errors
157 images
opensfm @ 1
Time Elapsed: 05:31:07

2018-02-11 09:13:44,284 DEBUG: Undistorting image 2017_0909_115002_078.JPG
2018-02-11 09:13:48,060 DEBUG: Undistorting image 2017_0909_115148_124.JPG
2018-02-11 09:13:51,842 DEBUG: Undistorting image 2017_0909_114819_028.JPG
2018-02-11 09:13:55,615 DEBUG: Undistorting image 2017_0909_115521_230.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm compute_depthmaps /var/www/data/b6f2428d-06ca-4526-ac44-e5e2ec2d4955/opensfm
2018-02-11 09:14:34,366 INFO: Computing neighbors
2018-02-11 09:16:01,914 INFO: Computing depthmap for image 2017_0909_114741_010.JPG with PATCH_MATCH
2018-02-11 09:17:18,349 INFO: Computing depthmap for image 2017_0909_115321_170.JPG with PATCH_MATCH
2018-02-11 09:18:36,423 INFO: Computing depthmap for image 2017_0909_115757_306.JPG with PATCH_MATCH
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 154, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by bryanibit** [comment]
I have met the same problem! I used the tx2 and met the following when computing depth map with lund dataset.
```
2018-05-15 16:12:36,787 INFO: Computing neighbors
2018-05-15 16:12:38,703 INFO: Computing depthmap for image 026.jpg with PATCH_MATCH
2018-05-15 16:12:39,273 INFO: Computing depthmap for image 025.jpg with PATCH_MATCH
2018-05-15 16:12:39,847 INFO: Computing depthmap for image 022.jpg with PATCH_MATCH
2018-05-15 16:12:40,456 INFO: Computing depthmap for image 015.jpg with PATCH_MATCH
Traceback (most recent call last):
  File "/opt/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/opt/OpenSfM/opensfm/commands/compute_depthmaps.py", line 25, in run
    dense.compute_depthmaps(data, graph, reconstructions[0])
  File "/opt/OpenSfM/opensfm/dense.py", line 36, in compute_depthmaps
    parallel_map(compute_depthmap_catched, arguments, processes)
  File "/opt/OpenSfM/opensfm/context.py", line 38, in parallel_map
    return list(e.map(func, args))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 719, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 584, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 382, in __get_result
    raise self._exception
loky.process_executor.BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending.
```

**Comment by PeterSprague** [comment]
@bryanibit I think your issue could more related to running out of memory.  Have you tried to lower the cores used for processing, which in turn lowers the RAM requirements?
