### ISSUE TITLE
Write error using python2.7

### ISSUE THREAD

**Issue by dakotabenjamin** [mapillary/OpenSfM#297]
Ran into an error trying to run export_geocoords
```
[DEBUG]   running PYTHONPATH=/home/dmb2/db-odm/SuperBuild/install/lib/python2.7/dist-packages /home/dmb2/db-odm/SuperBuild/src/opensfm/bin/opensfm export_geocoords /home/dmb2/db-odm/tests/test_data/opensfm --transformation --proj '+proj=utm +zone=17 +ellps=WGS84 +datum=WGS84 +units=m +no_defs '
Traceback (most recent call last):
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/commands/export_geocoords.py", line 66, in run
    self._write_transformation(transformation, output_path)
  File "/home/dmb2/db-odm/SuperBuild/src/opensfm/opensfm/commands/export_geocoords.py", line 106, in _write_transformation
    fout.write(' '.join(map(str, row)))
TypeError: write() argument 1 must be unicode, not str
Traceback (most recent call last):
  File "/home/dmb2/db-odm/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/home/dmb2/db-odm/scripts/run_opensfm.py", line 188, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm, reconstruction.georef.projection.srs))
  File "/home/dmb2/db-odm/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

I quickly solved this by changing the strings in line 105-106 to unicode: 
```
fout.write(u' '.join(map(str, row)))
fout.write(u'\n')
```
Is this an acceptable change for a PR?

**Comment by PeterSprague** [comment]
Same error, will try solution

**Comment by dakotabenjamin** [comment]
Thanks @paulinus !!!
