### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str for export_bundler

### ISSUE THREAD

**Issue by PeterSprague** [mapillary/OpenSfM#325]
New unicode vs string error on new master build

See PR: Change string to unicode in write_transformation #299 

2018-05-18 01:50:51,196 INFO: Pruning depthmap for image 2017_1016_133156_078.JPG
2018-05-18 01:50:51,830 INFO: Pruning depthmap for image 2017_1016_133647_208.JPG
2018-05-18 01:51:04,118 INFO: Merging depthmaps
[DEBUG]   running PYTHONPATH=/usr/local/lib/python2.7/dist-packages /usr/local/src/OpenSfM/bin/export_bundler /var/www/data/c76b8eb0-2457-461c-ae86-2809ae15cf31/opensfm
Traceback (most recent call last):
  File "/usr/local/src/OpenSfM/bin/export_bundler", line 48, in <module>
    io.export_bundler(images, reconstructions, track_graph, bundle_file_path, list_file_path)
  File "/usr/local/src/OpenSfM/opensfm/io.py", line 652, in export_bundler
    fout.writelines('\n'.join(lines) + '\n')
TypeError: write() argument 1 must be unicode, not str
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/run_opensfm.py", line 173, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

opensfm/io.py
'\n' --> u'\n'
line 652 
657
681
?702
?719
?721
?741 
?742
773
?821

Will work on and submit PR

**Comment by paulinus** [comment]
Thanks for finding out. I'm going to go ahead and use `unicode_literals` so that all literals are unicode and we don't need to explicitly mark them.

**Comment by YanNoun** [comment]
Was probably caused by OpenGV, which was removed here : https://github.com/mapillary/OpenSfM/pull/553
