### ISSUE TITLE
Error running "bin/opensfm_run_all data/berlin"

### ISSUE THREAD

**Issue by jhss** [mapillary/OpenSfM#341]
My OS is Mac OS Siera.
I followed all instructions in README and I entered "bin/opensfm_run_all data/berlin" on my terminal.
But I got an error 

```
(env) sjhui-MacBook-Pro:OpensfM songjuhong$ bin/opensfm_run_all data/berlin
bin/opensfm_run_all: line 7: /Users/songjuhong/Documents/Programming/Python/Python: is a directory
```

I don't know how can I solve it.

**Comment by paulinus** [comment]
It seems there is an error on the environment. Do you get the same error when running
```
/usr/bin/env python
```
?

**Comment by KyriakosZantis** [comment]
I  have a different problem on running "bin/opensfm_run_all data/berlin"

sudo ./bin/opensfm_run_all data/berlin
2018-09-19 16:30:56,795 INFO: Loading existing EXIF for 02.jpg
2018-09-19 16:30:56,795 INFO: Loading existing EXIF for 03.jpg
2018-09-19 16:30:56,795 INFO: Loading existing EXIF for 01.jpg
2018-09-19 16:30:57,546 INFO: Extracting ROOT_HAHOG features for image 02.jpg
2018-09-19 16:30:57,831 INFO: Extracting ROOT_HAHOG features for image 03.jpg
2018-09-19 16:30:58,114 INFO: Extracting ROOT_HAHOG features for image 01.jpg
2018-09-19 16:30:58,555 INFO: Matching 3 image pairs
2018-09-19 16:30:58,916 INFO: Matching 02.jpg  -  1 / 3
2018-09-19 16:30:59,233 INFO: Matching 01.jpg  -  2 / 3
2018-09-19 16:30:59,569 INFO: Matching 03.jpg  -  3 / 3
2018-09-19 16:30:59,742 DEBUG: 02.jpg - 03.jpg has 975 candidate matches
2018-09-19 16:30:59,743 DEBUG: Robust matching time : 0.000689029693604s
2018-09-19 16:30:59,743 DEBUG: Full matching 901 / 975, time: 0.826929092407s
2018-09-19 16:31:00,120 DEBUG: 01.jpg - 03.jpg has 405 candidate matches
2018-09-19 16:31:00,120 DEBUG: Robust matching time : 0.000534057617188s
2018-09-19 16:31:00,120 DEBUG: Full matching 348 / 405, time: 0.887475013733s
2018-09-19 16:31:00,913 DEBUG: 01.jpg - 02.jpg has 1450 candidate matches
2018-09-19 16:31:00,913 DEBUG: Robust matching time : 0.000697135925293s
2018-09-19 16:31:00,913 DEBUG: Full matching 1320 / 1450, time: 0.793071985245s
2018-09-19 16:31:01,384 INFO: reading features
2018-09-19 16:31:01,432 DEBUG: Merging features onto tracks
2018-09-19 16:31:01,450 DEBUG: Good tracks: 1858
2018-09-19 16:31:01,909 INFO: Starting incremental reconstruction
Traceback (most recent call last):
  File "/home/graphicslab/Desktop/Rise/programs/openmvg/OpenSfM-master/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/graphicslab/Desktop/Rise/programs/openmvg/OpenSfM-master/opensfm/commands/reconstruct.py", line 21, in run
    report = reconstruction.incremental_reconstruction(data)
  File "/home/graphicslab/Desktop/Rise/programs/openmvg/OpenSfM-master/opensfm/reconstruction.py", line 1161, in incremental_reconstruction
    pairs = compute_image_pairs(common_tracks, data)
  File "/home/graphicslab/Desktop/Rise/programs/openmvg/OpenSfM-master/opensfm/reconstruction.py", line 416, in compute_image_pairs
    result = parallel_map(_compute_pair_reconstructability, args, processes)
  File "/home/graphicslab/Desktop/Rise/programs/openmvg/OpenSfM-master/opensfm/context.py", line 38, in parallel_map
    return list(e.map(func, args))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 788, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 589, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 381, in __get_result
    raise self._exception
loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

what might be?

**Comment by KyriakosZantis** [comment]
i reinstall opensfm and everyhting was okey
