### ISSUE TITLE
ImportError: /usr/lib/libboost_python.so.1.66.0: undefined symbol: PyString_InternFromString

### ISSUE THREAD

**Issue by Smallha61109** [mapillary/OpenSfM#344]
Hello,
I am using python3 as default. I am able to build setup.py successfully without any error, but while I try to  execute `./bin/opensfm_run_all data/berlin` I got this error:

> Traceback (most recent call last):
  File "/home/gary/project/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/gary/project/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    from . import extract_metadata
  File "/home/gary/project/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/gary/project/OpenSfM/opensfm/dataset.py", line 14, in <module>
    from opensfm import io
  File "/home/gary/project/OpenSfM/opensfm/io.py", line 18, in <module>
    from opensfm import features
  File "/home/gary/project/OpenSfM/opensfm/features.py", line 9, in <module>
    from opensfm import csfm
ImportError: /usr/lib/libboost_python.so.1.66.0: undefined symbol: PyString_InternFromString

Seems like it is using python2's boost instead of python3's. Is there any suggestion on how to fix this?

**Comment by paulinus** [comment]
In executable scripts, we are using the shebang `#!/usr/bin/env python`. This is calling python2 in most systems.

As of now, the simplest solution to run using python3 is to call the `opensfm`  using as
```
python3 opensfm command path/to/dataset
```

You can edit the `opensfm_run_all` script to do so as
```
#!/usr/bin/env bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

python3 $DIR/opensfm extract_metadata $1
python3 $DIR/opensfm detect_features $1
python3 $DIR/opensfm match_features $1
python3 $DIR/opensfm create_tracks $1
python3 $DIR/opensfm reconstruct $1
python3 $DIR/opensfm mesh $1
python3 $DIR/opensfm undistort $1
python3 $DIR/opensfm compute_depthmaps $1
```
