### ISSUE TITLE
Unable to reconstruct data

### ISSUE THREAD

**Issue by pavithraezhil** [mapillary/OpenSfM#370]
sudo docker run -v /data/lund:/data/berlin -ti mapillary/opensfm /bin/sh -c "bin/opensfm_run_all /data/berlin"
Traceback (most recent call last):
  File "/source/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/source/OpenSfM/opensfm/commands/match_features.py", line 30, in run
    pairs, preport = match_candidates_from_metadata(images, exifs, data)
  File "/source/OpenSfM/opensfm/commands/match_features.py", line 187, in match_candidates_from_metadata
    gps_neighbors, max_distance)
  File "/source/OpenSfM/opensfm/commands/match_features.py", line 110, in match_candidates_by_distance
    tree = spatial.cKDTree(points)
  File "scipy/spatial/ckdtree.pyx", line 495, in scipy.spatial.ckdtree.cKDTree.__init__ (scipy/spatial/ckdtree.cxx:5441)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2268, in amax
    out=out, keepdims=keepdims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

--------------------------------
Should I make a change in the python file?

A few details: I am running it using the docker image. This is my command: 
sudo docker run -v /data/lund:/data/berlin -ti mapillary/opensfm /bin/sh -c "bin/opensfm_run_all  /data/berlin"

**Comment by qwertpi** [comment]
Did you ever solve this?
