### ISSUE TITLE
Error during depthmaps merging

### ISSUE THREAD

**Issue by seankovacs** [mapillary/OpenSfM#379]
Having some trouble running this on a set of equirectangular images. It keeps crashing on the "Merging depthmaps" section with the follow trace:
```
Traceback (most recent call last):
  File "/home/ubuntu/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/ubuntu/OpenSfM/opensfm/commands/compute_depthmaps.py", line 25, in run
    dense.compute_depthmaps(data, graph, reconstructions[0])
  File "/home/ubuntu/OpenSfM/opensfm/dense.py", line 57, in compute_depthmaps
    merge_depthmaps(data, reconstruction)
  File "/home/ubuntu/OpenSfM/opensfm/dense.py", line 228, in merge_depthmaps
    points = np.concatenate(points)
ValueError: need at least one array to concatenate
```

Here is the full stdout
```
Running using Python command: python
2018-11-16 19:59:32,683 INFO: Loading existing EXIF for 7eb72f28-d453-4b91-821a-0c241603da32.jpg
2018-11-16 19:59:32,684 INFO: Loading existing EXIF for 8d060331-36af-4f29-a780-9d7936cef77c.jpg
2018-11-16 19:59:32,684 INFO: Loading existing EXIF for cebdabcf-2fcc-4fb4-9b70-71f725d7e15e (1).jpg
2018-11-16 19:59:33,476 INFO: Extracting ROOT_HAHOG features for image 7eb72f28-d453-4b91-821a-0c241603da32.jpg
2018-11-16 19:59:33,777 INFO: Extracting ROOT_HAHOG features for image 8d060331-36af-4f29-a780-9d7936cef77c.jpg
2018-11-16 19:59:34,061 INFO: Extracting ROOT_HAHOG features for image cebdabcf-2fcc-4fb4-9b70-71f725d7e15e (1).jpg
2018-11-16 19:59:34,622 INFO: Matching 3 image pairs
2018-11-16 19:59:35,078 INFO: Matching 7eb72f28-d453-4b91-821a-0c241603da32.jpg  -  1 / 3
2018-11-16 19:59:35,498 INFO: Matching cebdabcf-2fcc-4fb4-9b70-71f725d7e15e (1).jpg  -  2 / 3
2018-11-16 19:59:35,911 INFO: Matching 8d060331-36af-4f29-a780-9d7936cef77c.jpg  -  3 / 3
2018-11-16 19:59:37,225 DEBUG: 7eb72f28-d453-4b91-821a-0c241603da32.jpg - cebdabcf-2fcc-4fb4-9b70-71f725d7e15e (1).jpg has 29 candidate matches
2018-11-16 19:59:38,494 DEBUG: 8d060331-36af-4f29-a780-9d7936cef77c.jpg - cebdabcf-2fcc-4fb4-9b70-71f725d7e15e (1).jpg has 14 candidate matches
2018-11-16 19:59:39,313 DEBUG: 7eb72f28-d453-4b91-821a-0c241603da32.jpg - 8d060331-36af-4f29-a780-9d7936cef77c.jpg has 126 candidate matches
2018-11-16 19:59:39,578 DEBUG: Robust matching time : 0.264617919922s
2018-11-16 19:59:39,578 DEBUG: Full matching 65 / 126, time: 1.77522706985s
2018-11-16 19:59:40,107 INFO: reading features
2018-11-16 19:59:40,190 DEBUG: Merging features onto tracks
2018-11-16 19:59:40,191 DEBUG: Good tracks: 65
2018-11-16 19:59:40,621 INFO: Starting incremental reconstruction
2018-11-16 19:59:40,632 INFO: Starting reconstruction with 7eb72f28-d453-4b91-821a-0c241603da32.jpg and 8d060331-36af-4f29-a780-9d7936cef77c.jpg
2018-11-16 19:59:40,717 INFO: Two-view reconstruction inliers: 65 / 65
2018-11-16 19:59:40,721 INFO: Triangulated: 65
2018-11-16 19:59:40,722 DEBUG: Ceres Solver Report: Iterations: 3, Initial cost: 2.380271e+00, Final cost: 2.374420e+00, Termination: CONVERGENCE
2018-11-16 19:59:40,727 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 2.375246e+00, Final cost: 2.372026e+00, Termination: CONVERGENCE
2018-11-16 19:59:40,756 DEBUG: Ceres Solver Report: Iterations: 51, Initial cost: 3.489004e+00, Final cost: 2.573165e+00, Termination: NO_CONVERGENCE
2018-11-16 19:59:40,756 INFO: Removed outliers: 0
2018-11-16 19:59:40,758 INFO: -------------------------------------------------------
2018-11-16 19:59:40,790 DEBUG: Ceres Solver Report: Iterations: 51, Initial cost: 2.584473e+00, Final cost: 2.567300e+00, Termination: NO_CONVERGENCE
2018-11-16 19:59:40,790 INFO: Removed outliers: 0
2018-11-16 19:59:40,794 INFO: Reconstruction 0: 2 images, 65 points
2018-11-16 19:59:40,794 INFO: 1 partial reconstructions in total.
2018-11-16 19:59:41,644 DEBUG: Undistorting the reconstruction
2018-11-16 19:59:42,152 DEBUG: Undistorting image 7eb72f28-d453-4b91-821a-0c241603da32.jpg
2018-11-16 19:59:42,554 DEBUG: Undistorting image 7eb72f28-d453-4b91-821a-0c241603da32.jpg
2018-11-16 19:59:43,007 DEBUG: Undistorting image 7eb72f28-d453-4b91-821a-0c241603da32.jpg
2018-11-16 19:59:43,432 DEBUG: Undistorting image 8d060331-36af-4f29-a780-9d7936cef77c.jpg
2018-11-16 19:59:43,432 DEBUG: Undistorting image 8d060331-36af-4f29-a780-9d7936cef77c.jpg
2018-11-16 19:59:43,433 DEBUG: Undistorting image 8d060331-36af-4f29-a780-9d7936cef77c.jpg
2018-11-16 19:59:45,640 INFO: Computing neighbors
2018-11-16 19:59:45,643 INFO: Merging depthmaps
Traceback (most recent call last):
  File "/home/ubuntu/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/ubuntu/OpenSfM/opensfm/commands/compute_depthmaps.py", line 25, in run
    dense.compute_depthmaps(data, graph, reconstructions[0])
  File "/home/ubuntu/OpenSfM/opensfm/dense.py", line 57, in compute_depthmaps
    merge_depthmaps(data, reconstruction)
  File "/home/ubuntu/OpenSfM/opensfm/dense.py", line 228, in merge_depthmaps
    points = np.concatenate(points)
ValueError: need at least one array to concatenate
```

Thoughts?

**Comment by paulinus** [comment]
Looks like only 2 images and 65 points were reconstructed. By default, depth estimation requires at least 3 images to see a point in order to reconstruct it. So it did not generate any point.

The simplest solution is to take more images.

We have added a warning for such a case.
