### ISSUE TITLE
When I run the sample,I got the error below,who can help me,thanks

### ISSUE THREAD

**Issue by xiangxji** [mapillary/OpenSfM#389]
data/test/  is my demo resource directory.

[root@********** bin]# ./opensfm_run_all ../data/test
Running using Python command: python
Traceback (most recent call last):
  File "/opt/OpenSfM-master/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/opt/OpenSfM-master/opensfm/commands/__init__.py", line 2, in <module>
    from . import extract_metadata
  File "/opt/OpenSfM-master/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/opt/OpenSfM-master/opensfm/dataset.py", line 13, in <module>
    from opensfm import io
  File "/opt/OpenSfM-master/opensfm/io.py", line 18, in <module>
    from opensfm import features
  File "/opt/OpenSfM-master/opensfm/features.py", line 9, in <module>
    from opensfm import csfm
ImportError: /usr/lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard

about this libpango problem,I have not found any solution to solve it.

**Comment by paulinus** [comment]
The module `csfm.so` should not be linked to libpango. Not sure what is happening here. Did the compilation work as is, or did you need to change anything?

**Comment by YanNoun** [comment]
No answer in a while, closing.
