### ISSUE TITLE
Import CV2 error

### ISSUE THREAD

**Issue by kwurz** [mapillary/OpenSfM#401]
Hi, I installed OpenSfM on an EC2 with the provided dockerfile. When I go to run the bin/opensfm_run_all berlin command I get the following error:

ubuntu@ip-172-31-4-35:~/OpenSfM$ bin/opensfm_run_all data/berlin                              
 Running using Python command: python                                                           
Traceback (most recent call last):                                                               
File "/home/ubuntu/OpenSfM/bin/opensfm", line 10, in from opensfm import commands                                                                 File "/home/ubuntu/OpenSfM/opensfm/commands/__init__.py", line 2, in from . import extract_metadata                                                               File "/home/ubuntu/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in from opensfm import dataset                                                                  
File "/home/ubuntu/OpenSfM/opensfm/dataset.py", line 13, in from opensfm import io                                                                       File "/home/ubuntu/OpenSfM/opensfm/io.py", line 13, in import cv2                                                                                 ImportError: No module named cv2
--

It looks like I have an issue with Opencv, but I had no errors building OpenSfM. Has anyone else encountered this?

**Comment by YanNoun** [comment]
@kwurz make sure you've installed `python-opencv` and it is in your `PYTHONPATH`.
