### ISSUE TITLE
Hyphens in GCP file breaks processing

### ISSUE THREAD

**Issue by ChipwizBen** [mapillary/OpenSfM#412]
Filing on behalf of WebODM: https://github.com/OpenDroneMap/WebODM/issues/648#issuecomment-479878943

An issues exists whereby processing a GCP file that references files with hyphens in their names fails to process correctly.

E.g. This does not work:
```
+proj=utm +zone=60G +ellps=WGS84 +datum=WGS84 +units=m +no_defs
373587.267613245 5453776.31470008 62 365 446 1517E3F8-545D-11E9-AB00-2DFF18339E5A.JPG
373593.617824043 5453757.40217389 62.1 301 464 159ED656-545D-11E9-AAA2-30FF18339E5A.JPG
373587.882779595 5453776.17031264 62.1 341 329 159ED656-545D-11E9-AAA2-30FF18339E5A.JPG
```

But this does work:
```
+proj=utm +zone=60G +ellps=WGS84 +datum=WGS84 +units=m +no_defs
373587.267613245 5453776.31470008 62 365 446 1517E3F8_545D_11E9_AB00_2DFF18339E5A.JPG
373593.617824043 5453757.40217389 62.1 301 464 159ED656_545D_11E9_AAA2_30FF18339E5A.JPG
373587.882779595 5453776.17031264 62.1 341 329 159ED656_545D_11E9_AAA2_30FF18339E5A.JPG
```

The application exits with an error similar to:
```
2019-04-02 16:40:50,024 INFO: Starting incremental reconstruction 
Traceback (most recent call last): 
File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in &lt;module&gt; command.run(args) 
File "/code/SuperBuild/src/opensfm/opensfm/commands/reconstruct.py", line 21, in run report = reconstruction.incremental_reconstruction(data) 
File "/code/SuperBuild/src/opensfm/opensfm/reconstruction.py", line 1158, in incremental_reconstruction gcp = data.load_ground_control_points() 
File "/code/SuperBuild/src/opensfm/opensfm/dataset.py", line 671, in load_ground_control_points fin, self.load_reference_lla(), exif) File "/code/SuperBuild/src/opensfm/opensfm/io.py", line 429, in read_ground_control_points_list for line in lines] 
File "/code/SuperBuild/src/opensfm/opensfm/io.py", line 373, in _read_gcp_list_line d = exif[shot_id] KeyError: 'FF9466AA-545C-11E9-9194-96FE18339E5A.JPG' 
Traceback (most recent call last): File "/code/run.py", line 47, in &lt;module&gt; plasm.execute(niter=1) 
File "/code/scripts/run_opensfm.py", line 136, in process (context.pyopencv_path, context.opensfm_path, tree.opensfm)) 
File "/code/opendm/system.py", line 34, in run raise 
Exception("Child returned {}".format(retcode)) 
Exception: Child returned 1
```

**Comment by smathermather** [comment]
Per https://github.com/OpenDroneMap/WebODM/issues/648 this issue is with NodeODM and should be closed here. @ChipwizBen -- can you close this? Cheers.
