### ISSUE TITLE
Images with no 'date take' exif data throws exception 

### ISSUE THREAD

**Issue by BarryReidPropeller** [mapillary/OpenSfM#42]
```
Extracting focal lengths for image DJI_0241.JPG
Traceback (most recent call last):
  File "/source/OpenSfM/bin/focal_from_exif", line 49, in <module>
    d = exif.extract_exif_from_file(data.load_image(image))
  File "/source/OpenSfM/opensfm/exif.py", line 87, in extract_exif_from_file
    d = exif_data.extract_exif()
  File "/source/OpenSfM/opensfm/exif.py", line 210, in extract_exif
    capture_time = self.extract_capture_time()
  File "/source/OpenSfM/opensfm/exif.py", line 197, in extract_capture_time
    d = datetime.datetime.strptime(s, '%Y:%m:%d %H:%M:%S')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y:%m:%d %H:%M:%S'
Traceback (most recent call last):
  File "/source/OpenSfM/bin/mesh", line 22, in <module>
    graph = data.load_tracks_graph()
  File "/source/OpenSfM/opensfm/dataset.py", line 280, in load_tracks_graph
    with open(self.__tracks_graph_file()) as fin:
IOError: [Errno 2] No such file or directory: '/data/output/tracks.csv'
done
```

**Comment by paulinus** [comment]
Thanks for reporting. The error should now be silent  https://github.com/mapillary/OpenSfM/commit/461c952913fa9cdbb5617ca2ac08e11198df6dfc
