### ISSUE TITLE
TypeError in get_mm_per_unit() 

### ISSUE THREAD

**Issue by sabado** [mapillary/OpenSfM#424]
I'm trying to use opensfm with a Canon PowerShot Camera SX600HS.  When i try to run opensfm_run_all i'm gotting a TypeError python error. I really dont understand too much python but it looks like exif tags are bad or something like that between PowerShot Camera and Opensfm format.

This is the result of the command:  `./bin/opensfm_run_all data/box`

```
./bin/opensfm_run_all data/box
Running using Python command: python
2019-06-01 00:33:52,660 INFO: Extracting EXIF for IMG_4076.JPG
2019-06-01 00:33:52,661 INFO: IMG_4076.JPG
Traceback (most recent call last):
  File "/root/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/root/OpenSfM/opensfm/commands/extract_metadata.py", line 36, in run
    d = self._extract_exif(image, data)
  File "/root/OpenSfM/opensfm/commands/extract_metadata.py", line 65, in _extract_exif
    d = exif.extract_exif_from_file(data.open_image_file(image))
  File "/root/OpenSfM/opensfm/exif.py", line 95, in extract_exif_from_file
    d = exif_data.extract_exif()
  File "/root/OpenSfM/opensfm/exif.py", line 298, in extract_exif
    focal_35, focal_ratio = self.extract_focal()
  File "/root/OpenSfM/opensfm/exif.py", line 187, in extract_focal
    self.extract_sensor_width(),
  File "/root/OpenSfM/opensfm/exif.py", line 197, in extract_sensor_width
    mm_per_unit = self.get_mm_per_unit(resolution_unit)
TypeError: get_mm_per_unit() takes exactly 1 argument (2 given)
```

I looked into the exif information obtained from the jpg image of the camera by running `identify -verbose IMG_4076.JPG` where  i found `  exif:FocalPlaneResolutionUnit: 2 ` is two. 

I have to change the exif by hand or the PowerShot data isn't enought to made a reconstruction? I missing something?

Thanks in advice!

Exif from  picture
```
Image: IMG_4076.JPG
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 3456x3456+0+0
  Resolution: 180x180
  Print size: 19.2x19.2
  Units: PixelsPerInch
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Pixels: 11943936
    Red:
      min: 43 (0.168627)
      max: 255 (1)
      mean: 117.253 (0.459817)
      standard deviation: 61.8604 (0.24259)
      kurtosis: -0.47276
      skewness: 1.10283
      entropy: 0.849361
    Green:
      min: 39 (0.152941)
      max: 255 (1)
      mean: 100.659 (0.39474)
      standard deviation: 42.8422 (0.168009)
      kurtosis: 2.10885
      skewness: 1.59641
      entropy: 0.853851
    Blue:
      min: 34 (0.133333)
      max: 255 (1)
      mean: 92.143 (0.361345)
      standard deviation: 42.2859 (0.165827)
      kurtosis: 4.16126
      skewness: 1.98151
      entropy: 0.850427
  Image statistics:
    Overall:
      min: 34 (0.133333)
      max: 255 (1)
      mean: 103.352 (0.405301)
      standard deviation: 49.8339 (0.195427)
      kurtosis: 1.83628
      skewness: 1.67616
      entropy: 0.851213
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 3456x3456+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 90
  Orientation: TopLeft
  Properties:
    date:create: 2019-06-01T03:38:58-03:00
    date:modify: 2013-12-31T21:04:58-03:00
    exif:ApertureValue: 149/32
    exif:ColorSpace: 1
    exif:ComponentsConfiguration: 1, 2, 3, 0
    exif:CompressedBitsPerPixel: 3/1
    exif:CustomRendered: 0
    exif:DateTime: 2014:01:01 00:04:59
    exif:DateTimeDigitized: 2014:01:01 00:04:59
    exif:DateTimeOriginal: 2014:01:01 00:04:59
    exif:DigitalZoomRatio: 3456/3456
    exif:ExifImageLength: 3456
    exif:ExifImageWidth: 3456
    exif:ExifOffset: 246
    exif:ExifVersion: 48, 50, 51, 48
    exif:ExposureBiasValue: 0/3
    exif:ExposureMode: 0
    exif:ExposureTime: 1/13
    exif:FileSource: 3
    exif:Flash: 16
    exif:FlashPixVersion: 48, 49, 48, 48
    exif:FNumber: 50/10
    exif:FocalLength: 12382/1000
    exif:FocalPlaneResolutionUnit: 2
    exif:FocalPlaneXResolution: 4608000/243
    exif:FocalPlaneYResolution: 3456000/182
    exif:GPSInfo: 6538
    exif:GPSVersionID: 2, 3, 0, 0
    exif:ImageDescription:                                
    exif:InteroperabilityOffset: 6428
    exif:ISOSpeedRatings: 1600
    exif:Make: Canon
    exif:MakerNote: 31, 0, 1, 0, 3, 0, 50, 0, 0, 0, 118, 4, 0, 0, 3, 0, 3, 0, 4, 0, 0, 0, 218, 4, 0, 0, 4, 0, 3, 0, 34, 0, 0, 0, 226, 4, 0, 0, 6, 0, 2, 0, 28, 0, 0, 0, 38, 5, 0, 0, 7, 0, 2, 0, 22, 0, 0, 0, 66, 5, 0, 0, 8, 0, 4, 0, 1, 0, 0, 0, 108, 208, 20, 0, 13, 0, 4, 0, 130, 3, 0, 0, 88, 5, 0, 0, 16, 0, 4, 0, 1, 0, 0, 0, 0, 0, 103, 3, 19, 0, 3, 0, 4, 0, 0, 0, 96, 19, 0, 0, 24, 0, 1, 0, 0, 1, 0, 0, 104, 19, 0, 0, 25, 0, 3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 28, 0, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 29, 0, 3, 0, 16, 0, 0, 0, 104, 20, 0, 0, 30, 0, 4, 0, 1, 0, 0, 0, 0, 4, 0, 1, 31, 0, 3, 0, 69, 0, 0, 0, 136, 20, 0, 0, 34, 0, 3, 0, 208, 0, 0, 0, 18, 21, 0, 0, 35, 0, 4, 0, 2, 0, 0, 0, 178, 22, 0, 0, 38, 0, 3, 0, 49, 0, 0, 0, 186, 22, 0, 0, 39, 0, 3, 0, 21, 0, 0, 0, 28, 23, 0, 0, 40, 0, 1, 0, 16, 0, 0, 0, 70, 23, 0, 0, 45, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 46, 0, 3, 0, 20, 0, 0, 0, 86, 23, 0, 0, 47, 0, 3, 0, 17, 0, 0, 0, 126, 23, 0, 0, 49, 0, 3, 0, 6, 0, 0, 0, 160, 23, 0, 0, 50, 0, 4, 0, 7, 0, 0, 0, 172, 23, 0, 0, 51, 0, 4, 0, 4, 0, 0, 0, 200, 23, 0, 0, 53, 0, 4, 0, 4, 0, 0, 0, 216, 23, 0, 0, 55, 0, 4, 0, 2, 0, 0, 0, 232, 23, 0, 0, 56, 0, 7, 0, 8, 0, 0, 0, 240, 23, 0, 0, 154, 0, 4, 0, 5, 0, 0, 0, 248, 23, 0, 0, 208, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0, 255, 255, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 3, 0, 1, 0, 6, 64, 0, 0, 255, 127, 255, 255, 164, 31, 194, 1, 100, 0, 149, 0, 244, 0, 255, 255, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 128, 13, 128, 13, 0, 0, 0, 0, 255, 255, 0, 0, 255, 127, 255, 127, 0, 0, 0, 0, 255, 255, 120, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 96, 0, 192, 0, 0, 0, 149, 0, 118, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 55, 0, 0, 0, 149, 0, 122, 0, 0, 0, 0, 0, 244, 255, 250, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 73, 77, 71, 58, 80, 111, 119, 101, 114, 83, 104, 111, 116, 32, 83, 88, 54, 48, 48, 32, 72, 83, 32, 74, 80, 69, 71, 0, 70, 105, 114, 109, 119, 97, 114, 101, 32, 86, 101, 114, 115, 105, 111, 110, 32, 49, 46, 48, 48, 0, 18, 0, 0, 0, 27, 3, 0, 0, 251, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 1, 0, 0, 112, 1, 0, 0, 32, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 1, 0, 0, 28, 2, 0, 0, 186, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 238, 255, 255, 255, 237, 255, 255, 255, 236, 255, 255, 255, 226, 255, 255, 255, 218, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 10, 0, 0, 0, 1, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 191, 1, 0, 0, 29, 2, 0, 0, 205, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65, 0, 0, 0, 158, 1, 0, 0, 17, 1, 0, 0, 9, 2, 0, 0, 20, 0, 0, 0, 201, 2, 0, 0, 0, 4, 0, 0, 118, 3, 0, 0, 156, 1, 0, 0, 15, 1, 0, 0, 231, 1, 0, 0, 61, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 231, 1, 0, 0, 61, 1, 0, 0, 7, 2, 0, 0, 255, 2, 0, 0, 151, 1, 0, 0, 19, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 202, 3, 0, 0, 57, 4, 0, 0, 71, 5, 0, 0, 12, 0, 0, 0, 151, 1, 0, 0, 19, 1, 0, 0, 154, 0, 0, 0, 193, 3, 0, 0, 135, 5, 0, 0, 16, 8, 0, 0, 193, 3, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 191, 1, 0, 0, 224, 1, 0, 0, 1, 0, 0, 0, 251, 1, 0, 0, 128, 1, 0, 0, 251, 255, 255, 255, 192, 0, 0, 0, 0, 0, 0, 0, 255, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 5, 0, 0, 5, 0, 0, 0, 144, 5, 0, 0, 154, 5, 0, 0, 169, 5, 0, 0, 184, 5, 0, 0, 198, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    exif:MaxApertureValue: 149/32
    exif:MeteringMode: 5
    exif:Model: Canon PowerShot SX600 HS
    exif:Orientation: 1
    exif:ResolutionUnit: 2
    exif:SceneCaptureType: 0
    exif:SensingMethod: 2
    exif:ShutterSpeedValue: 118/32
    exif:thumbnail:Compression: 6
    exif:thumbnail:InteroperabilityIndex: R98
    exif:thumbnail:InteroperabilityVersion: 48, 49, 48, 48
    exif:thumbnail:JPEGInterchangeFormat: 12788
    exif:thumbnail:JPEGInterchangeFormatLength: 3361
    exif:thumbnail:RelatedImageLength: 3456
    exif:thumbnail:RelatedImageWidth: 3456
    exif:thumbnail:ResolutionUnit: 2
    exif:thumbnail:XResolution: 180/1
    exif:thumbnail:YResolution: 180/1
    exif:UserComment: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    exif:WhiteBalance: 0
    exif:XResolution: 180/1
    exif:YCbCrPositioning: 2
    exif:YResolution: 180/1
    jpeg:colorspace: 2
    jpeg:sampling-factor: 2x1,1x1,1x1
    signature: 324c60c07c8284cd5a7348f55de11585202fd445551941c0d6705b67075b85ca
    unknown: 4
    xmp:Rating: 0
  Profiles:
    Profile-exif: 20988 bytes
    Profile-xmp: 3965 bytes
  Artifacts:
    filename: IMG_4076.JPG
    verbose: true
  Tainted: False
  Filesize: 2.191MB
  Number pixels: 11.94M
  Pixels per second: 79.63MB
  User time: 0.150u
  Elapsed time: 0:01.149
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
```

**Comment by sabado** [comment]
solved by adding self as first parameter of get_mm_per_unit()  

https://github.com/mapillary/OpenSfM/compare/master...sabado:patch-1

**Comment by GITNE** [comment]
What Python version do you run OpenSfM on? This may explain why we did not catch that sort of *missing* parameter…

**Comment by sabado** [comment]
@GITNE  i'm using Python 2.7.12

**Comment by Red025** [comment]
Running using Python command: python
2019-09-26 17:05:53,878 INFO: Extracting EXIF for DJI_0167.JPG
Traceback (most recent call last):
  File "/home/nesac/anaconda3/lib/python3.7/site-packages/xmltodict.py", line 309, in parse
    parser.ParseFile(xml_input)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nesac/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/nesac/OpenSfM/opensfm/commands/extract_metadata.py", line 35, in run
    d = self._extract_exif(image, data)
  File "/home/nesac/OpenSfM/opensfm/commands/extract_metadata.py", line 64, in _extract_exif
    d = exif.extract_exif_from_file(data.open_image_file(image))
  File "/home/nesac/OpenSfM/opensfm/exif.py", line 93, in extract_exif_from_file
    exif_data = EXIF(fileobj)
  File "/home/nesac/OpenSfM/opensfm/exif.py", line 133, in __init__
    self.xmp = get_xmp(fileobj)
  File "/home/nesac/OpenSfM/opensfm/exif.py", line 108, in get_xmp
    xdict = x2d.parse(xmp_str)
  File "/home/nesac/anaconda3/lib/python3.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 150

I am getting this error while loading new images into opensfm. Can anyone please tell me how to slove this issue?
