### ISSUE TITLE
Problem running demo: undefined symbol

### ISSUE THREAD

**Issue by os-gabe** [mapillary/OpenSfM#480]
I was able to get everything built but when I try to run the demo I get the following error which I'm having a hard time debugging:

`$ bin/opensfm_run_all data/berlin`
```
Running using Python command: python
Traceback (most recent call last):
  File "/home/gabe/code/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/gabe/code/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    from . import extract_metadata
  File "/home/gabe/code/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/gabe/code/OpenSfM/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/home/gabe/code/OpenSfM/opensfm/io.py", line 20, in <module>
    from opensfm import features
  File "/home/gabe/code/OpenSfM/opensfm/features.py", line 10, in <module>
    from opensfm import csfm
ImportError: /home/gabe/code/OpenSfM/opensfm/csfm.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE
```

I'm on Ubuntu 18.04. I installed the requirements via pip and apt. Any help is much appreciated.

**Comment by paulinus** [comment]
Great that you solved it, @os-gabe. Multiple opencv version problems are tricky because cmake searches for opencv independently of python so you can end up linking to a different one.
