### ISSUE TITLE
#TypeError: argument must have 'read' attribute

### ISSUE THREAD

**Issue by Red025** [mapillary/OpenSfM#483]
Running using Python command: python
2019-09-26 17:05:53,878 INFO: Extracting EXIF for DJI_0167.JPG
Traceback (most recent call last):
  File "/home/nesac/anaconda3/lib/python3.7/site-packages/xmltodict.py", line 309, in parse
    parser.ParseFile(xml_input)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nesac/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/nesac/OpenSfM/opensfm/commands/extract_metadata.py", line 35, in run
    d = self._extract_exif(image, data)
  File "/home/nesac/OpenSfM/opensfm/commands/extract_metadata.py", line 64, in _extract_exif
    d = exif.extract_exif_from_file(data.open_image_file(image))
  File "/home/nesac/OpenSfM/opensfm/exif.py", line 93, in extract_exif_from_file
    exif_data = EXIF(fileobj)
  File "/home/nesac/OpenSfM/opensfm/exif.py", line 133, in __init__
    self.xmp = get_xmp(fileobj)
  File "/home/nesac/OpenSfM/opensfm/exif.py", line 108, in get_xmp
    xdict = x2d.parse(xmp_str)
  File "/home/nesac/anaconda3/lib/python3.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 150

I am getting this error while loading new images into opensfm. Can anyone please tell me how to slove this issue?

**Comment by GITNE** [comment]
Looks like the XMP metadata in your image file might be malformed. Does your image file carry any XMP metadata?

**Comment by Red025** [comment]
yes, my images has some metadata but those images were working fine when i constructed 3D model using webODM but its showing the above error while importing those image in OpenSfM. How can i solve that error?

**Comment by teliov** [comment]
Also had the same issue. It seems that the inclusion of the newline (`\n`) character in the xmp string causes this to happen. Replacing it with an empty string allowed the validation to pass. But this is only possible by editing osfm's code directly.

**Comment by BatFaceWayne** [comment]
Such issue could be easily resolved by omitting the process of reading  XMP metadata since the actual exif data extraction is done by exifread.
Try change the self.xmp = get_xmp(fileobj) to self.xmp=[] in the exif.py. That would not interfere much with the metadata. If you do want to use the XMP data, replace the '\n' in the strxmp might help.

**Comment by paulinus** [comment]
We have recently added a patch for parsing XMP that include escaped characters. https://github.com/mapillary/OpenSfM/issues/510#issuecomment-587003946
