### ISSUE TITLE
ModuleNotFoundError: No module named 'pyopengv'

### ISSUE THREAD

**Issue by apiszcz** [mapillary/OpenSfM#499]
The pyopengv .so builds and installs without error. However imports fail.
Is there another environment variable needed to add to the library path or?
Thank you.

```
/OpenSfM$ locate pyopengv
/usr/local/lib/python3/dist-packages/pyopengv.cpython-37m-x86_64-linux-gnu.so

Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopengv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyopengv'

y1@ubuntu:~/OpenSfM$ bin/opensfm_run_all  data/berlin
Running using Python command: python3
Traceback (most recent call last):
  File "/home/y1/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/y1/OpenSfM/opensfm/commands/__init__.py", line 4, in <module>
    from . import match_features
  File "/home/y1/OpenSfM/opensfm/commands/match_features.py", line 9, in <module>
    from opensfm import matching
  File "/home/y1/OpenSfM/opensfm/matching.py", line 3, in <module>
    import pyopengv
ModuleNotFoundError: No module named 'pyopengv'

```

**Comment by apiszcz** [comment]
SOLUTION per (https://github.com/laurentkneip/opengv/issues/84)

```
cd /usr/local/lib/python3.7/dist-packages/
ln -s /usr/local/lib/python3/dist-packages/pyopengv.cpython-37m-x86_64-linux-gnu.so .
```

**Comment by mlm74** [comment]
Thanks!

**Comment by RadwaSK** [comment]
I've done the solution above and it has't made me any good. Same issue exists.

**Comment by paulinus** [comment]
opengv is no longer needed. So, things might work better for you now, @RadwaSK

**Comment by RadwaSK** [comment]
@paulinus  When I run the example provided in the OpenSFM documentation, it runs some files which import pyopengv, and then I get this error

**Comment by paulinus** [comment]
@RadwaSK, can you check that you are using latest `master` commit. Opengv is not used anymore.

**Comment by RadwaSK** [comment]
@paulinus Okay, I'll make sure and try it again in a few and let you know of the results. Thanks, either way!
