### ISSUE TITLE
OpenSfM Cannot parse EXIF from DJI drone image

### ISSUE THREAD

**Issue by SwiftGust** [mapillary/OpenSfM#502]
Trying to extract metadata from the image took from DJI P4P causes following error
where 

sample image : 
![100_0090_0052](https://user-images.githubusercontent.com/13569579/69817289-9a583b00-123d-11ea-9374-5752b9f491ce.JPG)

```
$ python3 bin/opensfm extract_metadata data/berlin/
2019-11-29 00:14:46,631 INFO: Extracting EXIF for 100_0090_0052.JPG
Traceback (most recent call last):
  File "bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/uvify/OpenSfM/opensfm/commands/extract_metadata.py", line 35, in run
    d = self._extract_exif(image, data)
  File "/home/uvify/OpenSfM/opensfm/commands/extract_metadata.py", line 64, in _extract_exif
    d = exif.extract_exif_from_file(data.open_image_file(image))
  File "/home/uvify/OpenSfM/opensfm/exif.py", line 93, in extract_exif_from_file
    exif_data = EXIF(fileobj)
  File "/home/uvify/OpenSfM/opensfm/exif.py", line 134, in __init__
    self.xmp = get_xmp(fileobj)
  File "/home/uvify/OpenSfM/opensfm/exif.py", line 109, in get_xmp
    xdict = x2d.parse(((xmp_str)))
  File "/usr/local/lib/python3.6/dist-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 150

```

**Comment by SwiftGust** [comment]
Using python 2.7 allows extract_metadata to work, but still no luck in python 3.6

**Comment by paulinus** [comment]
That image contains an XML which is corrupted as far as I understand
```
<x:xmpmeta xmlns:x="adobe:ns:meta/">\\n <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\\n  <rdf:Description rdf:about="DJI Meta Data"\\n    xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\\n    xmlns:exif="http://ns.adobe.com/exif/1.0/"\\n    xmlns:xmp="http://ns.adobe.com/xap/1.0/"\\n    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"\\n    xmlns:dc="http://purl.org/dc/elements/1.1/"\\n    xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"\\n    xmlns:drone-dji="http://www.dji.com/drone-dji/1.0/"\\n   xmp:ModifyDate="2019-11-22"\\n   xmp:CreateDate="2019-11-22"\\n   tiff:Make="DJI"\\n   tiff:Model="FC6310R"\\n   dc:format="image/jpg"\\n   drone-dji:AbsoluteAltitude="+256.54"\\n   drone-dji:RelativeAltitude="+49.98"\\n   drone-dji:GpsLatitude="36.28071927"\\n   drone-dji:GpsLongtitude="126.63984228"\\n   drone-dji:GimbalRollDegree="+0.00"\\n   drone-dji:GimbalYawDegree="-60.90"\\n   drone-dji:GimbalPitchDegree="-89.90"\\n   drone-dji:FlightRollDegree="+3.30"\\n   drone-dji:FlightYawDegree="-61.30"\\n   drone-dji:FlightPitchDegree="-0.40"\\n   drone-dji:FlightXSpeed="+0.90"\\n   drone-dji:FlightYSpeed="-1.70"\\n   drone-dji:FlightZSpeed="+0.00"\\n   drone-dji:CamReverse="0"\\n   drone-dji:GimbalReverse="0"\\n   drone-dji:SelfData="Undefined"\\n   drone-dji:CalibratedFocalLength="3666.666504"\\n   drone-dji:CalibratedOpticalCenterX="2736.000000"\\n   drone-dji:CalibratedOpticalCenterY="1824.000000"\\n   drone-dji:RtkFlag="50"\\n   drone-dji:RtkStdLon="0.01311"\\n   drone-dji:RtkStdLat="0.01187"\\n   drone-dji:RtkStdHgt="0.02293"\\n   drone-dji:DewarpData=" 2018-09-08;3678.690000000000,3671.610000000000,6.010000000000,18.770000000000,-0.263993000000,0.104334000000,0.000239492000,0.000599958000,-0.028034000000"\\n   drone-dji:DewarpFlag="0"\\n   crs:Version="7.0"\\n   crs:HasSettings="False"\\n   crs:HasCrop="False"\\n   crs:AlreadyApplied="False">\\n  </rdf:Description>\\n </rdf:RDF>\\n</x:xmpmeta>
```
Note the `\\n` characters which are not interpreted as whitespace by the XML parser.

You can patch opensfm to work with this particular image with this change
```
diff --git a/opensfm/exif.py b/opensfm/exif.py
index 28ff6b5..476a3ef 100644
--- a/opensfm/exif.py
+++ b/opensfm/exif.py
@@ -105,6 +105,7 @@ def get_xmp(fileobj):
 
     if xmp_start < xmp_end:
         xmp_str = img_str[xmp_start:xmp_end + 12]
+        xmp_str = xmp_str.replace('\\n', '\n')
         xdict = x2d.parse(xmp_str)
         xdict = xdict.get('x:xmpmeta', {})
         xdict = xdict.get('rdf:RDF', {})
```
not sure if we can find a general patch that we could include in the library.

**Comment by SwiftGust** [comment]
Sorry for late response.
This patch works on python2.7 & python3.6 both with image took from DJI and berlin dataset without an issue.

**Comment by sfikas** [comment]
Images took with my DJI drone (Matrice M200 this time) lead also to a similar problem. The only difference is that in my case also '\r' characters show up, so an extra command in the same spirit does the trick. i.e.
```
xmp_str = xmp_str.replace('\\r', '\r')
xmp_str = xmp_str.replace('\\n', '\n')
```

**Comment by paulinus** [comment]
@sfikas, we have recently added a patch to handle this problem. Could you check if your DJI images can be parsed with current master without modifications?

**Comment by sfikas** [comment]
Indeed, it works ok! Thanks.
(Maybe the issue should close as 'fixed' then?)
