### ISSUE TITLE
Fedora : compilation issues (GCC 9 and OpenMP)

### ISSUE THREAD

**Issue by Majstor** [mapillary/OpenSfM#520]
Hi,
I try to compile on Fedora 31 OpenSfM. It fails with OpenMP :
```
[ 37%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kmeans.c.o
Dans le fichier inclus depuis /home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.h:21,
                 depuis /home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:363:
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c: Dans la fonction « _vl_kmeans_quantize_f »:
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/mathop.h:92:37: erreur: « vl_infinity_d » non spécifié dans la région « parallel » englobante
   92 | #define VL_INFINITY_D (vl_infinity_d.value)
      |                       ~~~~~~~~~~~~~~^~~~~~~
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:685:34: note: dans l'expansion de la macro « VL_INFINITY_D »
  685 |       TYPE bestDistance = (TYPE) VL_INFINITY_D ;
      |                                  ^~~~~~~~~~~~~
Dans le fichier inclus depuis /home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:1782:
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:672:9: erreur: région « parallel » englobante
  672 | #pragma omp parallel default(none) \
      |         ^~~
Dans le fichier inclus depuis /home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:1788:
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c: Dans la fonction « _vl_kmeans_quantize_d »:
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:685:27: erreur: « vl_infinity_d » non spécifié dans la région « parallel » englobante
  685 |       TYPE bestDistance = (TYPE) VL_INFINITY_D ;
/home/majstor/Documents/Travaux/PROGRAMMATION/OpenSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:672:9: erreur: région « parallel » englobante
  672 | #pragma omp parallel default(none) \
      |         ^~~
make[2]: *** [CMakeFiles/vl.dir/build.make:271: CMakeFiles/vl.dir/third_party/vlfeat/vl/kmeans.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/vl.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
[ 39%] Building CXX object CMakeFiles/gtest.dir/third_party/gtest/gmock_main.cc.o
[ 41%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/nldiffusion_functions.cpp.o
[ 42%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/utils.cpp.o
[ 44%] Linking CXX static library libakaze.a
[ 44%] Built target akaze
[ 46%] Linking CXX static library libgtest.a
[ 46%] Built target gtest
[ 48%] Linking CXX static library libbundle.a
[ 48%] Built target bundle
make: *** [Makefile:95: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j4'], cwd='cmake_build')
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.
```

**Comment by Majstor** [comment]
OK, it's an incompatibility between GCC >= 9 and OpenMP, see here : https://www.gnu.org/software/gcc/gcc-9/porting_to.html

Can anyone do the necessary modifications ?

**Comment by StefanoFrazzetto** [comment]
Should be fixed by https://github.com/mapillary/OpenSfM/commit/01b5987496e974662a113731cc5bfa8d01ad00ec
