### ISSUE TITLE
Python 3.7 OpenSfM 0.3 demo error

### ISSUE THREAD

**Issue by romavlasov** [mapillary/OpenSfM#522]
Hi,

I've installed OpenSfM and run the demo 'bin/opensfm undistort data/berlin' but it fails with reason:

Traceback (most recent call last):
  File "bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/Users/romanvlasov/Sources/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    from . import extract_metadata
  File "/Users/romanvlasov/Sources/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/Users/romanvlasov/Sources/OpenSfM/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/Users/romanvlasov/Sources/OpenSfM/opensfm/io.py", line 20, in <module>
    from opensfm import features
  File "/Users/romanvlasov/Sources/OpenSfM/opensfm/features.py", line 10, in <module>
    from opensfm import csfm
ImportError: dlopen(/Users/romanvlasov/Sources/OpenSfM/opensfm/csfm.cpython-37m-darwin.so, 2): Symbol not found: ___kmpc_dispatch_init_4
  Referenced from: /Users/romanvlasov/Sources/OpenSfM/opensfm/csfm.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/romanvlasov/Sources/OpenSfM/opensfm/csfm.cpython-37m-darwin.so

Could you help me to solve this issue? If you need additional info please ask.

**Comment by moopene36607** [comment]
You might try to build a docker container to walk-around the problem.
