### ISSUE TITLE
using export_openmvs

### ISSUE THREAD

**Issue by tub-sgg** [mapillary/OpenSfM#549]
Traceback (most recent call last):
  File "bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/alex/Documents/openSFM/OpenSfM/opensfm/commands/export_openmvs.py", line 27, in run
    self.export(reconstructions[0], graph, data)
  File "/home/alex/Documents/openSFM/OpenSfM/opensfm/commands/export_openmvs.py", line 43, in export
    image_path = udata._undistorted_image_file(shot.id)
NameError: name 'udata' is not defined
 what's wrong with it??

**Comment by YanNoun** [comment]
Hi,

Thanks for reporting the bug. It has been fixed on latest master here : https://github.com/mapillary/OpenSfM/commit/ff1cad80b287a6153e4c0a6972dc7f745cbcfee0

Let me know if that fixes your issue.

Yann

**Comment by tub-sgg** [comment]
sorry for being late reply. I followed the instruction and export .mvs file.But when I use OpenMVS to deal with this .mvs file, always failed to continue to get the result.It seems smething wrong with this file 
[scene.zip](https://github.com/mapillary/OpenSfM/files/4312675/scene.zip)

**Comment by YanNoun** [comment]
Hi @tub-sgg , it probably have been fixed here : https://github.com/mapillary/OpenSfM/pull/713
