### ISSUE TITLE
Cannot build target robust on macosx 10.14 and 10.15

### ISSUE THREAD

**Issue by paulpauca** [mapillary/OpenSfM#559]
I'm having trouble installing OpenSFM in Mac OS X 10.14 and 10.15. Everything works up until trying: python setup.py build.  I cannot figure out how to get pass this. Can someone help?

[ 94%] Built target robust
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j4'], cwd='cmake_build')
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

**Comment by Wolfffff** [comment]
Same issue here!

**Comment by Wolfffff** [comment]
Update: Assuming most people already know this but using [opensfm-docker-base](https://github.com/paulinus/opensfm-docker-base) is an easy workaround here. Gets everything working without fighting macos.

**Comment by Wolfffff** [comment]
Try running reinstall/installing LLVM `brew install LLVM`. I ended up doing this and it recovered my installing issues on 10.15.4.

**Comment by bugracoskun** [comment]
`brew install LLVM` worked for me. Thanks!
