### ISSUE TITLE
Import error: cannot import 'pyfeatures' from 'opensfm' 

### ISSUE THREAD

**Issue by Juuustin** [mapillary/OpenSfM#572]
Hi,
I'd like to run the demo, but there is an import error, what should I do to fix it ?
Thank you for any suggestions!

`(SFM) objloc@deeplearning:~/OBJLOC/OpenSfM$ bin/opensfm_run_all data/berlin
Running using Python command: python3
Traceback (most recent call last):
  File "/home/objloc/OBJLOC/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/objloc/OBJLOC/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    from . import extract_metadata
  File "/home/objloc/OBJLOC/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/objloc/OBJLOC/OpenSfM/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/home/objloc/OBJLOC/OpenSfM/opensfm/io.py", line 20, in <module>
    from opensfm import features
  File "/home/objloc/OBJLOC/OpenSfM/opensfm/features.py", line 10, in <module>
    from opensfm import pyfeatures
ImportError: cannot import name 'pyfeatures' from 'opensfm' (/home/objloc/OBJLOC/OpenSfM/opensfm/__init__.py)
`

**Comment by Juuustin** [comment]
solved

**Comment by RadwaSK** [comment]
How did you solve it?

**Comment by Juuustin** [comment]
> How did you solve it?
> I've same issue currently.

Just close the anaconda environment and reinstall it again. 
There might be some conflicts from anaconda
