### ISSUE TITLE
Error in executing plot_inliers

### ISSUE THREAD

**Issue by mac516** [mapillary/OpenSfM#588]
Hello

I have error in executing plot_inliers. Error message is follow:
-------------------------------------------------------------------------------------------------
Plotting tracks for image00293.jpg - image00296.jpg...
Traceback (most recent call last):
  File "/source/OpenSfM/bin/plot_inliers", line 968, in <module>
    create_tracks_figure(image1, image2, ds, save, single)
    plot_bootstrapped_reconstruction(fw, ip, 4, p1, p2, robust_tracks, linked_tracks, graph, data)
  File "/source/OpenSfM/bin/plot_inliers", line 589, in plot_bootstrapped_reconstruction
    reconstruction, _, _ = reconstruct.bootstrap_reconstruction(data, graph, ip.im1, ip.im2, pm1, pm2)
TypeError: bootstrap_reconstruction() missing 1 required positional argument: 'p2'
-----------------------------------------------------------------------------------------------

The function "bootstrap_reconstruction" in reconstruction.py needs 7 parameters. However,  the function "reconstruct.bootstrap_reconstruction" in plot_inliers call with 6 parameters.

Is this bug?

**Comment by YanNoun** [comment]
Hi @mac516 , yes, it is a bug that we're going to address. Thank you for reporting.
