### ISSUE TITLE
Problems in "python setup.py build"

### ISSUE THREAD

**Issue by xin-peng** [mapillary/OpenSfM#595]
Hello, I am using Ubuntu 16.04 and I followed every step in https://www.opensfm.org/docs/building.html in order to install dependency. When I run "python setup.py build", it fails. 
```
Configuring for python 3.6...
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /home/xin/catkin_wsmap/devel/lib/libamd.a
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /home/xin/catkin_wsmap/devel/lib/libcamd.a
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /home/xin/catkin_wsmap/devel/lib/libcolamd.a
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /home/xin/catkin_wsmap/devel/lib/libccolamd.a
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found CHOLMOD library: /home/xin/catkin_wsmap/devel/lib/libcholmod.a
-- Found CHOLMOD header in: /usr/include/suitesparse
-- Found CXSPARSE library: /home/xin/catkin_wsmap/devel/lib/libcxsparse.a
-- Found SuiteSparseQR library: /home/xin/catkin_wsmap/devel/lib/libspqr.a
-- Found SuiteSparseQR header in: /usr/include/suitesparse
-- Found Intel Thread Building Blocks (TBB) library: /usr/lib/x86_64-linux-gnu/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/lib/x86_64-linux-gnu/libtbbmalloc.so
-- Found SuiteSparse_config library: /home/xin/catkin_wsmap/devel/lib/libsuitesparseconfig.a
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS library: /home/xin/catkin_wsmap/devel/lib/libmetis.so.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /home/xin/catkin_wsmap/devel/lib/cmake/gflags
-- Detected broken gflags install in: /home/xin/catkin_wsmap/devel/lib/cmake/gflags, version: 2.1.2 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.2
-- Found OpenCV: /home/xin/catkin_wsmap/devel (found version "3.2.0") 
-- Found OpenCV: /home/xin/catkin_wsmap/devel (found version "3.2.0") found components:  core imgproc calib3d imgcodecs 
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.10") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- pybind11 v2.2.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xin/ws/opengv/build/OpenSfM/cmake_build
Compiling extension...
Scanning dependencies of target foundation
[  3%] Built target gtest
[ 21%] Built target akaze
[ 48%] Built target vl
[ 51%] Built target test_main
[ 52%] Building CXX object foundation/CMakeFiles/foundation.dir/src/types.cc.o
[ 53%] Building CXX object foundation/CMakeFiles/foundation.dir/src/logger.cc.o
[ 54%] Building CXX object foundation/CMakeFiles/foundation.dir/src/numeric.cc.o
[ 55%] Linking CXX static library libfoundation.a
[ 55%] Built target foundation
Scanning dependencies of target dense
Scanning dependencies of target bundle
Scanning dependencies of target features
Scanning dependencies of target geometry
[ 56%] Building CXX object dense/CMakeFiles/dense.dir/src/depthmap.cc.o
[ 57%] Building CXX object bundle/CMakeFiles/bundle.dir/src/bundle_adjuster.cc.o
[ 59%] Building CXX object features/CMakeFiles/features.dir/src/akaze_bind.cc.o
[ 60%] Building CXX object geometry/CMakeFiles/geometry.dir/src/essential.cc.o
[ 61%] Linking CXX static library libdense.a
[ 61%] Built target dense
[ 62%] Building CXX object geometry/CMakeFiles/geometry.dir/src/triangulation.cc.o
[ 63%] Building CXX object features/CMakeFiles/features.dir/src/hahog.cc.o
[ 64%] Building CXX object features/CMakeFiles/features.dir/src/matching.cc.o
[ 65%] Linking CXX static library libfeatures.a
[ 65%] Built target features
[ 67%] Building CXX object geometry/CMakeFiles/geometry.dir/src/absolute_pose.cc.o
Scanning dependencies of target sfm
[ 68%] Building CXX object sfm/CMakeFiles/sfm.dir/src/tracks_manager.cc.o
[ 69%] Building CXX object sfm/CMakeFiles/sfm.dir/src/sfm_helpers.cc.o
[ 70%] Building CXX object geometry/CMakeFiles/geometry.dir/src/relative_pose.cc.o
In file included from /home/xin/ws/opengv/build/OpenSfM/opensfm/src/geometry/relative_pose.h:7:0,
                 from /home/xin/ws/opengv/build/OpenSfM/opensfm/src/geometry/src/relative_pose.cc:1:
/usr/local/include/ceres/tiny_solver_autodiff_function.h: In member function ‘bool ceres::TinySolverAutoDiffFunction<CostFunctor, kNumResiduals, kNumParameters, T>::operator()(const T*, T*, T*) const’:
/usr/local/include/ceres/tiny_solver_autodiff_function.h:106:29: error: ‘kImpossibleValue’ was not declared in this scope
       jet_residuals_[i].a = kImpossibleValue;
                             ^
[ 71%] Linking CXX static library libsfm.a
[ 71%] Built target sfm
Scanning dependencies of target pydense
[ 72%] Linking CXX executable dense_test
[ 73%] Building CXX object dense/CMakeFiles/pydense.dir/python/pybind.cc.o
[ 75%] Built target dense_test
Scanning dependencies of target pyfeatures
[ 76%] Building CXX object features/CMakeFiles/pyfeatures.dir/python/pybind.cc.o
[ 77%] Linking CXX static library libbundle.a
[ 77%] Built target bundle
[ 78%] Linking CXX executable sfm_test
CMakeFiles/sfm_test.dir/test/tracks_manager_test.cc.o: In function `testing::internal::TestFactoryImpl<(anonymous namespace)::TracksManagerTest_ReturnsShotsIDs_Test>::CreateTest()':
tracks_manager_test.cc:(.text+0x309): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[ 79%] Built target sfm_test
Scanning dependencies of target pysfm
[ 80%] Building CXX object sfm/CMakeFiles/pysfm.dir/python/pybind.cc.o
[ 81%] Linking CXX shared module /home/xin/ws/opengv/build/OpenSfM/opensfm/pysfm.cpython-36m-x86_64-linux-gnu.so
[ 82%] Linking CXX shared module /home/xin/ws/opengv/build/OpenSfM/opensfm/pyfeatures.cpython-36m-x86_64-linux-gnu.so
[ 84%] Linking CXX shared module /home/xin/ws/opengv/build/OpenSfM/opensfm/pydense.cpython-36m-x86_64-linux-gnu.so
geometry/CMakeFiles/geometry.dir/build.make:134: recipe for target 'geometry/CMakeFiles/geometry.dir/src/relative_pose.cc.o' failed
make[2]: *** [geometry/CMakeFiles/geometry.dir/src/relative_pose.cc.o] Error 1
CMakeFiles/Makefile2:675: recipe for target 'geometry/CMakeFiles/geometry.dir/all' failed
make[1]: *** [geometry/CMakeFiles/geometry.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Built target pysfm
[ 84%] Built target pyfeatures
[ 84%] Built target pydense
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j4'], cwd='cmake_build')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

'''
How can I fix it?

**Comment by moopene36607** [comment]
I also got an error while the docker -build running "python3 setup.py build"
OS = "CentOS Linux 7 (Core)"
Docker version = 18.09.3, build 774a1f4
Log：

```
Successfully installed Pillow-6.2.0 cloudpickle-0.4.0 joblib-0.13.2 loky-1.2.1 pyyaml-5.1
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found CHOLMOD header in: /usr/include/suitesparse
-- Found CXSPARSE library: /usr/lib/x86_64-linux-gnu/libcxsparse.so
-- Found SuiteSparseQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found SuiteSparseQR header in: /usr/include/suitesparse
-- Found Intel Thread Building Blocks (TBB) library: /usr/lib/x86_64-linux-gnu/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/lib/x86_64-linux-gnu/libtbbmalloc.so
-- Found SuiteSparse_config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "5.1.2")
-- Found Eigen: /usr/include/eigen3 (found version "3.3.4")
-- Found ceres: /usr/local/lib/libceres.a
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.1
-- Found Gflags: /usr/include
-- Found Glog: /usr/include
-- Found OpenCV: /usr (found version "3.2.0")
-- Found OpenCV: /usr (found version "3.2.0") found components:  core imgproc calib3d imgcodecs
CMake Error at CMakeLists.txt:54 (add_subdirectory):
  The source directory

    /source/OpenSfM/opensfm/src/third_party/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at bundle/CMakeLists.txt:26 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/source/OpenSfM/cmake_build/CMakeFiles/CMakeOutput.log".
Configuring for python 3.6...
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    configure_c_extension()
  File "setup.py", line 39, in configure_c_extension
    subprocess.check_call(cmake_command, cwd='cmake_build')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../opensfm/src', '-DPYTHON_EXECUTABLE=/usr/bin/python3']' returned non-zero exit status 1.
```

**Comment by Byastal** [comment]
I have encountered this problem. Have you solved it?

**Comment by moopene36607** [comment]
You may try older version:
https://github.com/mapillary/OpenSfM/commit/9dd730779b71252287dd53e3f31d4c2388f03cd2#diff-3254677a7917c6c01f55212f86c57fbf

```
FROM paulinus/opensfm-docker-base:python3

COPY . /source/OpenSfM

WORKDIR /source/OpenSfM

RUN pip3 install -r requirements.txt && \
    python3 setup.py build
```

**Comment by Byastal** [comment]
Thank you. I have successfully solved this problem！

**Comment by YanNoun** [comment]
Closing as the problem was solved.
