### ISSUE TITLE
TypeError in align_reconstruction_orientation_prior_similarity

### ISSUE THREAD

**Issue by saurabhmitra** [mapillary/OpenSfM#626]
I'm running the default `bin/opensfm_run_all data/berlin` as per this guide: https://www.opensfm.org/docs/using.html. I get a crash here:
```
Xp:  [None, [-5.59390578888069, -5.151720240904979, 1.999995470046997], [0.8170872077700586, -4.224413149717293, 1.9999985489994287]]
/Users/saurabhmitra/Documents/OpenSfM/opensfm/align.py:174: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Xp = np.array(Xp)
Traceback (most recent call last):
  File "/Users/saurabhmitra/Documents/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/Users/saurabhmitra/Documents/OpenSfM/opensfm/commands/reconstruct.py", line 23, in run
    incremental_reconstruction(data, tracks_manager)
  File "/Users/saurabhmitra/Documents/OpenSfM/opensfm/reconstruction.py", line 1345, in incremental_reconstruction
    data, tracks_manager, graph_inliers, reconstruction, remaining_images, camera_priors, gcp)
  File "/Users/saurabhmitra/Documents/OpenSfM/opensfm/reconstruction.py", line 1197, in grow_reconstruction
    align_reconstruction(reconstruction, gcp, config)
  File "/Users/saurabhmitra/Documents/OpenSfM/opensfm/align.py", line 17, in align_reconstruction
    res = align_reconstruction_similarity(reconstruction, gcp, config)
  File "/Users/saurabhmitra/Documents/OpenSfM/opensfm/align.py", line 58, in align_reconstruction_similarity
    res = align_reconstruction_orientation_prior_similarity(reconstruction, config, gcp)
  File "/Users/saurabhmitra/Documents/OpenSfM/opensfm/align.py", line 187, in align_reconstruction_orientation_prior_similarity
    Xp.std(axis=0).max() < 0.01)      # All GPS points are the same.
  File "/Users/saurabhmitra/Library/Python/3.7/lib/python/site-packages/numpy/core/_methods.py", line 234, in _std
    keepdims=keepdims)
  File "/Users/saurabhmitra/Library/Python/3.7/lib/python/site-packages/numpy/core/_methods.py", line 192, in _var
    arrmean = umr_sum(arr, axis, dtype, keepdims=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```
which happens because the first element of Xp is None. Since this happens on the provided example, I was wondering if something is wrong with my project setup. I'm using python 3.7.5 on Mac OS

**Comment by YanNoun** [comment]
There's a bug in the latest release (v0.5.0). Will be fixed in the hour and a new release will be issue in the following days.

**Comment by YanNoun** [comment]
It is fixed now.

**Comment by saurabhmitra** [comment]
thank you!!
