### ISSUE TITLE
[bug] navigation_graph

### ISSUE THREAD

**Issue by tomasparks** [mapillary/OpenSfM#652]
When I run navigation_graph on a dataset I get
> /home/opensfm/OpenSfM/bin/navigation_graph  /home/opensfm/data/berlin/

> Traceback (most recent call last):
>   File "/home/opensfm/OpenSfM/bin/navigation_graph", line 299, in <module>
>     rec_graph = create_optical_center_graph(recs, data.config)
>       File "/home/opensfm/OpenSfM/bin/navigation_graph", line 147, in create_optical_center_graph
>           optical_centers = np.vstack(optical_centers)
>             File "<__array_function__ internals>", line 5, in vstack
>               File "/usr/lib/python3/dist-packages/numpy/core/shape_base.py", line 282, in vstack
>     return _nx.concatenate(arrs, 0)
>       File "<__array_function__ internals>", line 5, in concatenate
>  ValueError: need at least one array to concatenate

**Comment by YanNoun** [comment]
Hi @tomasparks , indeed, it looks like a bug, we're going to address it, thank you for reporting.
