### ISSUE TITLE
No attribute'focal_x' error occurred when export_colmap

### ISSUE THREAD

**Issue by chaoji90** [mapillary/OpenSfM#669]
I entered `/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/bin/opensfm export_colmap "/home/zhangshuai/lastest/ODM/odm_test_data/opensfm"` to export the colmap format then I got following issue:
```
Traceback (most recent call last):
  File "/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/bin/opensfm_main.py", line 8, in <module>
    commands.command_runner(commands.opensfm_commands)
  File "/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/opensfm/commands/command_runner.py", line 27, in command_runner
    command.run(args)
  File "/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/opensfm/commands/command.py", line 12, in run
    self.run_impl(data, args)
  File "/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/opensfm/commands/export_colmap.py", line 10, in run_impl
    export_colmap.run_dataset(dataset, args.binary)
  File "/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/opensfm/actions/export_colmap.py", line 62, in run_dataset
    images_map, camera_map = export_cameras(data, db)
  File "/home/zhangshuai/lastest/ODM/SuperBuild/src/opensfm/opensfm/actions/export_colmap.py", line 283, in export_cameras
    parameters = np.array((camera.focal_x*normalizer,
AttributeError: 'opensfm.pygeometry.Camera' object has no attribute 'focal_x'
```
The content of camera_models.json is 
```
{
    "v2 sony voigtlander nokton classic 35mm f1.4 7952 5304 brown 0.9722 rgb": {
        "projection_type": "brown",
        "width": 7952,
        "height": 5304,
        "focal_x": 0.9722222222222222,
        "focal_y": 0.9722222222222222,
        "c_x": 0.0,
        "c_y": 0.0,
        "k1": 0.0,
        "k2": 0.0,
        "p1": 0.0,
        "p2": 0.0,
        "k3": 0.0
    }
}
```
What is wrong or is there any way to find out the problem? By the way,  this problem appeared when I tried to convert the output of opensfm in ODM into the colmap format.

**Comment by pierotofy** [comment]
ODM's version of OpenSfM has been modified to use a single focal length in the brown model. Either process the dataset with `--camera-lens perspective` or use the code from https://github.com/mapillary/OpenSfM to process your data.

This is not a bug in OpenSfM (if anything it's a bug in ODM's fork).

**Comment by chaoji90** [comment]
> ODM's version of OpenSfM has been modified to use a single focal length in the brown model. Either process the dataset with `--camera-lens perspective` or use the code from https://github.com/mapillary/OpenSfM to process your data.
> 
> This is not a bug in OpenSfM (if anything it's a bug in ODM's fork).

Thanks for the reply, you definitely gave a good hint, I will try to figure this out.
