### ISSUE TITLE
FileNotFoundError: [Errno 2] File or directory does not exist: '../data/berlin/undistorted/reconstruction.json' when trying to reconstruct 'berlin'

### ISSUE THREAD

**Issue by luisEMEBA** [mapillary/OpenSfM#704]
Hi everybody! hope you to be having a good day. Recently I've installed OpenSfM with all it's dependencies (I guess) so now I'm trying to do the test reconstruction with 'berlin' but when I try I get the next error: 

2021-02-07 09:23:37,342 INFO: Loading existing EXIF for 02.jpg
2021-02-07 09:23:37,343 INFO: Loading existing EXIF for 01.jpg
2021-02-07 09:23:37,343 INFO: Loading existing EXIF for 03.jpg
2021-02-07 09:23:40,924 INFO: Skip recomputing ROOT_HAHOG features for image 02.jpg
2021-02-07 09:23:40,924 INFO: Skip recomputing ROOT_HAHOG features for image 01.jpg
2021-02-07 09:23:40,925 INFO: Skip recomputing ROOT_HAHOG features for image 03.jpg
2021-02-07 09:23:44,625 INFO: Matching 3 image pairs
2021-02-07 09:23:44,648 INFO: Computing pair matching with 5 processes
2021-02-07 09:23:44,674 DEBUG: Image 03.jpg matches: 0 out of 0
2021-02-07 09:23:45,130 DEBUG: Masking 0 / 4436 (0.00) features for 02.jpg
2021-02-07 09:23:45,134 DEBUG: Masking 0 / 4656 (0.00) features for 01.jpg
2021-02-07 09:23:45,548 DEBUG: Masking 0 / 4743 (0.00) features for 03.jpg
2021-02-07 09:23:47,974 DEBUG: Matching 01.jpg and 02.jpg.  Matcher: FLANN (symmetric) T-desc: 3.269 T-robust: 0.029 T-total: 3.298 Matches: 1288 Robust: 1251 Success: True
2021-02-07 09:23:48,350 DEBUG: Matching 02.jpg and 03.jpg.  Matcher: FLANN (symmetric) T-desc: 3.655 T-robust: 0.016 T-total: 3.672 Matches: 830 Robust: 761 Success: True
2021-02-07 09:23:48,350 DEBUG: Image 02.jpg matches: 1 out of 1
2021-02-07 09:23:48,570 DEBUG: Matching 01.jpg and 03.jpg.  Matcher: FLANN (symmetric) T-desc: 0.588 T-robust: 0.005 T-total: 0.593 Matches: 348 Robust: 321 Success: True
2021-02-07 09:23:48,570 DEBUG: Image 01.jpg matches: 2 out of 2
2021-02-07 09:23:48,573 INFO: Matched 3 pairs for 3 ref_images (perspective-perspective: 3) in 3.948230093003076 seconds (1.3160773143342037 seconds/pair).
2021-02-07 09:23:51,836 INFO: reading features
2021-02-07 09:23:51,958 DEBUG: Merging features onto tracks
2021-02-07 09:23:52,055 DEBUG: Good tracks: 1749
2021-02-07 09:23:55,573 INFO: Starting incremental reconstruction
2021-02-07 09:23:55,714 INFO: 0 partial reconstructions in total.
Traceback (most recent call last):
  File "/home/user/Documentos/OpenSfM/bin/opensfm_main.py", line 15, in <module>
    commands.command_runner(commands.opensfm_commands, default_dataset_type)
  File "/home/user/Documentos/OpenSfM/opensfm/commands/command_runner.py", line 31, in command_runner
    command.run(data, args)
  File "/home/user/Documentos/OpenSfM/opensfm/commands/command.py", line 12, in run
    self.run_impl(data, args)
  File "/home/user/Documentos/OpenSfM/opensfm/commands/compute_depthmaps.py", line 11, in run_impl
    compute_depthmaps.run_dataset(dataset, args.subfolder, args.interactive)
  File "/home/user/Documentos/OpenSfM/opensfm/actions/compute_depthmaps.py", line 19, in run_dataset
    reconstructions = udataset.load_undistorted_reconstruction()
  File "/home/user/Documentos/OpenSfM/opensfm/dataset.py", line 866, in load_undistorted_reconstruction
    with io.open_rt(filename) as fin:
  File "/home/user/Documentos/OpenSfM/opensfm/io.py", line 771, in open_rt
    return open(path, "r", encoding="utf-8")
FileNotFoundError: [Errno 2] File or directory does not exist: '../data/berlin/undistorted/reconstruction.json'

It's the same with every data set I try, does anyone knows the reason of this error? thank you very much! 

Actually I'm using Xubuntu 20.

**Comment by fabianschenk** [comment]
Hi @luisEMEBA ,
The `reconstruction.json` is typically in the `data/berlin` folder and not in the undistorted subfolder.
The easiest way to run the whole pipeline is the following command:
```
bin/opensfm_run_all data/berlin
```

This runs all the feature detection, matching, reconstruction and a few more and puts everything into the `berlin` folder. After that, there should also be a `reconstruction.json` in the `data/berlin/undistorted` folder.

For me it looks like this:
```
2021-02-09 00:13:29,260 INFO: Starting incremental reconstruction
2021-02-09 00:13:29,374 INFO: Starting reconstruction with 01.jpg and 02.jpg
2021-02-09 00:13:29,431 INFO: Two-view reconstruction inliers: 1062 / 1062
2021-02-09 00:13:29,548 INFO: Triangulated: 1050
2021-02-09 00:13:29,571 DEBUG: Ceres Solver Report: Iterations: 4, Initial cost: 4.399111e+01, Final cost: 3.358312e+01, Termination: CONVERGENCE
2021-02-09 00:13:29,677 DEBUG: Ceres Solver Report: Iterations: 4, Initial cost: 3.543443e+01, Final cost: 3.140322e+01, Termination: CONVERGENCE
2021-02-09 00:13:29,810 DEBUG: Ceres Solver Report: Iterations: 17, Initial cost: 7.347875e+01, Final cost: 5.509539e+01, Termination: CONVERGENCE
2021-02-09 00:13:29,818 INFO: Removed outliers: 0
2021-02-09 00:13:29,819 INFO: -------------------------------------------------------
2021-02-09 00:13:29,825 INFO: 03.jpg resection inliers: 157 / 242
2021-02-09 00:13:29,829 DEBUG: Ceres Solver Report: Iterations: 6, Initial cost: 5.209073e+01, Final cost: 4.807658e+01, Termination: CONVERGENCE
2021-02-09 00:13:29,829 INFO: Adding 03.jpg to the reconstruction
2021-02-09 00:13:29,855 INFO: Re-triangulating
2021-02-09 00:13:30,163 DEBUG: Ceres Solver Report: Iterations: 43, Initial cost: 3.367070e+02, Final cost: 1.686588e+02, Termination: CONVERGENCE
2021-02-09 00:13:30,420 DEBUG: Ceres Solver Report: Iterations: 21, Initial cost: 2.597258e+02, Final cost: 2.353133e+02, Termination: CONVERGENCE
2021-02-09 00:13:30,431 INFO: Removed outliers: 5
2021-02-09 00:13:30,433 INFO: -------------------------------------------------------
2021-02-09 00:13:30,755 DEBUG: Ceres Solver Report: Iterations: 43, Initial cost: 2.255034e+02, Final cost: 2.176175e+02, Termination: CONVERGENCE
2021-02-09 00:13:30,766 INFO: Removed outliers: 0
2021-02-09 00:13:30,784 INFO: Reconstruction 0: 3 images, 1411 points
2021-02-09 00:13:30,784 INFO: 1 partial reconstructions in total.
```

**Comment by luisEMEBA** [comment]
Good day to you, @fabianschenk. First than all I wish to thank you for checking my issue. Well, I run the pipeline through the line `bin/opensfm_run_all data/berlin`. Look, I've documented the process with some screenshots: 

![1](https://user-images.githubusercontent.com/61065463/107374959-332b4d00-6ab6-11eb-8ef6-1e68ba81eedf.png)

Figure1: This is the content of the test folder before I ran the command (I've erased some files but got the same error with or without them).

![2](https://user-images.githubusercontent.com/61065463/107375094-5c4bdd80-6ab6-11eb-9716-84989fde3eb2.png)

Figure 2: This is me in the main directory seconds before running the command.

![3](https://user-images.githubusercontent.com/61065463/107375561-e005ca00-6ab6-11eb-8914-c585f562e52b.png)

Figure 3: This is the error I get after executing the command.

![4](https://user-images.githubusercontent.com/61065463/107375648-f7dd4e00-6ab6-11eb-8c42-c15e2184a9b8.png)

Figure 4: This is the `data/berlin` folder after running the command.

what have I tried? Well, till this moments I've tried to re-install the dependencies of the library many times, I also re-builded ceres solver and build from source OpenCV. I've tried too changing the directory to the principal partition, I've tried too build the OpenSfM pipeline as sudo, I'v tried too change the values of number of processes in config.yaml but still getting the same error. I've used the Open SfM pipeline many times before in Xubuntu 20, actually I'm trying it in Xubuntu 18. May I did some mistake in the installation process? Thank you very much for the atention.

**Comment by luisEMEBA** [comment]
Update: I've tried in Xubuntu 18 and got the same error I really don't know the reason of this error.

**Comment by fabianschenk** [comment]
Hi @luisEMEBA ,

puh, this seems like a tough one. 
Did you try to update the repo to the newest version, i.e. run a `git pull`, in the directory?
It's strange that it prints `Starting incremental reconstruction`, then does nothing and of course has 0 reconstructions then. This explains why the rest fails but I have no idea why it doesn't reconstruct. The matching and tracks are similar to what I get.
 
You can try going step-by-step through the `incremental_reconstruction` in `reconstruction.py`.

**Comment by luisEMEBA** [comment]
Hi there, @fabianschenk ! Thank you very much for your help, much apreciate it. I've repaired this error, more than repair I think is to find a way to solve this trouble, so if you or any other person is having the same issue I'll like to share the solution I found for Xubuntu 18.04, as is the same error in Xubuntu 20 I guess the way to fix it is too the same :) So let's go step by step.

This procedure consist into clone the latest version of OpenSfM at the time I'm writing this reply (0.5.1) and then download the source code from an older version (in my case I used 0.4.0 ) then go to the folder of this older version, copy and then paste all it's files into the latest OpenSfM version folder (the one you cloned) replacing the pre-existing files of the new version, then build the pipe line with `python3 setup.py build` and that's all, run `bin/opensfm_run_all data/berlin` and enjoy.

![1](https://user-images.githubusercontent.com/61065463/107451110-9ba91700-6b14-11eb-82a8-c6258ee3eb6a.png)
  Figure 1: clone the latest version from the git repository.

![2](https://user-images.githubusercontent.com/61065463/107451214-d0b56980-6b14-11eb-82a6-c3c019389cb3.png)
Figure 2: Download an older version from [https://github.com/mapillary/OpenSfM/releases](url) 

![3](https://user-images.githubusercontent.com/61065463/107451295-ff334480-6b14-11eb-949f-9626a3d0d963.png)
Figure 3: In my case I used the 0.4.0 version.

![4](https://user-images.githubusercontent.com/61065463/107454846-c480da80-6b1b-11eb-9a32-e264142fd380.png)
Figure 4: Copy all files in the older version's folder.

![5](https://user-images.githubusercontent.com/61065463/107455006-0d389380-6b1c-11eb-97df-1f97d04819b1.png)
Figure 5: Paste and replace them in the latest version's folder.

![6](https://user-images.githubusercontent.com/61065463/107455062-27727180-6b1c-11eb-9da8-c481b417955c.png)
Figure 6: Build Open SfM

![final](https://user-images.githubusercontent.com/61065463/107455104-3822e780-6b1c-11eb-809e-d993f8c698a2.png)
Figure 7: Enjoy!
