### ISSUE TITLE
Error when I use python setup.py

### ISSUE THREAD

**Issue by tranvanha1508** [mapillary/OpenSfM#770]
This is my computer display. What should I do ? Thank for help 
(sfm) D:\manhinh\Ki2Nam4\code\OpenSfM>python setup.py build
Configuring for python 3.7...
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
-- A library with LAPACK API found.
-- Found AMD library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/amd.lib
-- Failed to find SuiteSparse - Did not find AMD header (required SuiteSparse component).
-- Found CAMD library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/camd.lib
-- Failed to find SuiteSparse - Did not find CAMD header (required SuiteSparse component).
-- Found COLAMD library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/colamd.lib
-- Failed to find SuiteSparse - Did not find COLAMD header (required SuiteSparse component).
-- Found CCOLAMD library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/ccolamd.lib
-- Failed to find SuiteSparse - Did not find CCOLAMD header (required SuiteSparse component).
-- Found CHOLMOD library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/cholmod.lib
-- Failed to find SuiteSparse - Did not find CHOLMOD header (required SuiteSparse component).
-- Found CXSPARSE library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/cxsparse.lib
-- Found SuiteSparseQR library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/spqr.lib
-- Failed to find SuiteSparse - Did not find SUITESPARSEQR header (required SuiteSparse component).
-- Found SuiteSparse_config library: C:/Users/ADMIN/anaconda3/envs/sfm/Library/lib/suitesparseconfig.lib
-- Failed to find SuiteSparse - Failed to find either: SuiteSparse_config header & library (should be present in all SuiteSparse >= v4 installs), or UFconfig header (should be present in all SuiteSparse < v4 installs).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Failed to find some/all required components of SuiteSparse. (missing: AMD_FOUND CAMD_FOUND COLAMD_FOUND CCOLAMD_FOUND CHOLMOD_FOUND SUITESPARSEQR_FOUND SUITESPARSE_VERSION)
CMake Error at cmake/FindEigen.cmake:77 (MESSAGE):
  Failed to find Eigen - Could not find eigen3 include directory, set
  EIGEN_INCLUDE_DIR to path to eigen3 include directory, e.g.
  /usr/local/include/eigen3.
Call Stack (most recent call first):
  cmake/FindEigen.cmake:103 (EIGEN_REPORT_NOT_FOUND)
  CMakeLists.txt:37 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/manhinh/Ki2Nam4/code/OpenSfM/cmake_build/CMakeFiles/CMakeOutput.log".
See also "D:/manhinh/Ki2Nam4/code/OpenSfM/cmake_build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    configure_c_extension()
  File "setup.py", line 37, in configure_c_extension
    subprocess.check_call(cmake_command, cwd="cmake_build")
  File "C:\Users\ADMIN\anaconda3\envs\sfm\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../opensfm/src', '-DPYTHON_EXECUTABLE=C:\\Users\\ADMIN\\anaconda3\\envs\\sfm\\python.exe']' returned non-zero exit status 1.

**Comment by fabianschenk** [comment]
Hi @tranvanha1508 ,

It seems that either Eigen is not installed on your system or the paths are not set correctly.
I don't use Windows and can't reproduce the issue but maybe [this](https://roboticslab-uc3m.github.io/installation-guides/install-eigen.html) helps.
Good luck :D
