### ISSUE TITLE
Issue running: OpenCV Assertion Failed and Core Dumped

### ISSUE THREAD

**Issue by waltermorawa** [mapillary/OpenSfM#824]
Below, I have attached an issue I am having running OpenSfM with a dataset of 583 images. I am using a c-2 4vcpu from GCPs platform with ubuntu. I am able to run the sample datasets fine, which makes me wonder if there is something wrong with my images or my config file. I have tried HAHOG and AKAZE and run into the same issue. Thanks in advance. 

Config.yaml:
processes: 4                  # Number of threads to use
depthmap_min_consistent_views: 2      # Min number of views that should reconstruct a point for it to be valid
depthmap_save_debug_files: no         # Save debug files with partial reconstruction results
feature_process_size: 512 #Also tried 1024 and -1
bundle_use_gcp: yes
feature_type: AKAZE
akaze_dthreshold: 0.00001

OpenCV Error: Assertion failed (query.type() == type && indices.type() == CV_32S && dists.type() == dtype) in runKn
nSearch_, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/flann/src/miniflann.cpp, line 485
Traceback (most recent call last):
  File "/home/bigw124/OpenSfM/bin/opensfm_main.py", line 26, in <module>
    commands.opensfm_commands, create_default_dataset_context, dataset_choices=["opensfm"]
  File "/home/bigw124/OpenSfM/opensfm/commands/command_runner.py", line 37, in command_runner
    command.run(data, args)
  File "/home/bigw124/OpenSfM/opensfm/commands/command.py", line 12, in run
    self.run_impl(data, args)
  File "/home/bigw124/OpenSfM/opensfm/commands/match_features.py", line 11, in run_impl
    match_features.run_dataset(dataset)
  File "/home/bigw124/OpenSfM/opensfm/actions/match_features.py", line 14, in run_dataset
    pairs_matches, preport = matching.match_images(data, {}, images, images)
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 56, in match_images
    match_images_with_pairs(data, config_override, exifs, pairs),
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 80, in match_images_with_pairs
    matches = context.parallel_map(match_unwrap_args, args, processes, jobs_per_process)
  File "/home/bigw124/OpenSfM/opensfm/context.py", line 52, in parallel_map
    res = Parallel(batch_size=batch_size)(delayed(func)(arg) for arg in args)
  File "/home/waltermorawa/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/waltermorawa/.local/lib/python3.6/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/waltermorawa/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/waltermorawa/.local/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
 File "/home/waltermorawa/.local/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 200, in match_unwrap_args
    matches = match(im1, im2, camera1, camera2, data, config_override)
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 462, in match
    im1, im2, camera1, camera2, data, overriden_config
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 328, in _match_descriptors_impl
    overriden_config,
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 590, in match_flann_symmetric
    matches_ij = [(a, b) for a, b in match_flann(indexi, fj, config)]
  File "/home/bigw124/OpenSfM/opensfm/matching.py", line 572, in match_flann
    results, dists = index.knnSearch(f2, 2, params=search_params)
cv2.error: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/flann/src/miniflann.cpp:485: error: (-215) query.type() =
= type && indices.type() == CV_32S && dists.type() == dtype in function runKnnSearch_
terminate called without an active exception
/home/bigw124/OpenSfM/bin/opensfm: line 12:  2987 Aborted                 (core dumped) "$PYTHON" "$DIR"/opensfm_ma
in.py "$@"

**Comment by waltermorawa** [comment]
I'm starting to think that this issue is related to not enough RAM. I only have 16GB of ram and am trying to run 583 images. I will try with a more powerful VM and then update this issue.

**Comment by waltermorawa** [comment]
So, I had no problem running my images when I ran 10 of them. The problem arose from far too many images and not nearly enough ram. This is 583 photos and my vm only had 16 GB of ram. I will retry the 583 set with more ram and will update this issue.

**Comment by waltermorawa** [comment]
I can now confirm that I was able to run the dataset of 583 images on a c-16 gcp vm. It took about an hour to process.
