### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by lthiet** [mapillary/OpenSfM#834]
Hi,

I am trying to run the example test case command `bin/opensfm_run_all data/berlin` which results in this error:

```
(OpenSfM) lthiet@agatha:~/Code/OpenSfM$ bin/opensfm_run_all data/berlin
Traceback (most recent call last):
  File "/home/lthiet/Code/OpenSfM/bin/opensfm_main.py", line 9, in <module>
    from opensfm import commands
  File "/home/lthiet/Code/OpenSfM/opensfm/commands/__init__.py", line 1, in <module>
    from . import (
  File "/home/lthiet/Code/OpenSfM/opensfm/commands/align_submodels.py", line 1, in <module>
    from opensfm.actions import align_submodels
  File "/home/lthiet/Code/OpenSfM/opensfm/actions/align_submodels.py", line 1, in <module>
    from opensfm.large import metadataset
  File "/home/lthiet/Code/OpenSfM/opensfm/large/metadataset.py", line 10, in <module>
    from opensfm.dataset import DataSet
  File "/home/lthiet/Code/OpenSfM/opensfm/dataset.py", line 10, in <module>
    from opensfm import (
  File "/home/lthiet/Code/OpenSfM/opensfm/rig.py", line 9, in <module>
    import networkx as nx
  File "/home/lthiet/miniconda3/envs/OpenSfM/lib/python3.9/site-packages/networkx/__init__.py", line 84, in <module>
    import networkx.generators
  File "/home/lthiet/miniconda3/envs/OpenSfM/lib/python3.9/site-packages/networkx/generators/__init__.py", line 5, in <module>
    from networkx.generators.classic import *
  File "/home/lthiet/miniconda3/envs/OpenSfM/lib/python3.9/site-packages/networkx/generators/classic.py", line 21, in <module>
    from networkx.algorithms.bipartite.generators import complete_bipartite_graph
  File "/home/lthiet/miniconda3/envs/OpenSfM/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 12, in <module>
    from networkx.algorithms.dag import *
  File "/home/lthiet/miniconda3/envs/OpenSfM/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 2, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/lthiet/miniconda3/envs/OpenSfM/lib/python3.9/fractions.py)
```

I have installed dependencies accordingly except Pillow, which was set to version 8.0.0 because there was a dependency conflict. See issue #790 for more details on the dependency conflict.

I have also built and ran the docker image, after which the issue was not resolved.

How do I get past this import error without breaking the whole code?

**Comment by lthiet** [comment]
The issue is caused by Python 3.9. Using Python 3.8 works fine.
