### ISSUE TITLE
Building problem with python3 setup.py build

### ISSUE THREAD

**Issue by Mmmelvil** [mapillary/OpenSfM#868]
C:\Users\jinch\OneDrive\Desktop\OpenSfm\OpenSfM> python3 setup.py build
Configuring for python 3.8...
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    configure_c_extension()
  File "setup.py", line 43, in configure_c_extension
    subprocess.check_call(cmake_command, cwd="cmake_build")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

I do not quite understand why the specified file cannot be found.

**Comment by fabianschenk** [comment]
Hi @Mmmelvil ,

What have you tried to solve this issue? This does not seem to be related to OpenSfM but rather to the Python installation on Windows.

Best Fabian

**Comment by rdbch** [comment]
I had the same problem. I managed to solve this by installing cmake.
