### ISSUE TITLE
run errors on Ubuntu18

### ISSUE THREAD

**Issue by guijuzhejiang** [mapillary/OpenSfM#899]
I follow the 'https://opensfm.org/docs/building.html''s instruction but I got error below after i ran 'bin/opensfm_run_all data/berlin':
Traceback (most recent call last):
  File "/home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/bin/opensfm_main.py", line 6, in <module>
    from opensfm import commands
  File "/home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/opensfm/commands/__init__.py", line 1, in <module>
    from . import (
  File "/home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/opensfm/commands/align_submodels.py", line 1, in <module>
    from opensfm.actions import align_submodels
  File "/home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/opensfm/actions/align_submodels.py", line 1, in <module>
    from opensfm.large import metadataset
  File "/home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/opensfm/large/metadataset.py", line 7, in <module>
    from opensfm import io
  File "/home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/opensfm/io.py", line 9, in <module>
    from opensfm import context, features, geo, pygeometry, pymap, types
ImportError: /home/ray/Workspace/project/ORB_SLAM3/src/ref/OpenSfM/opensfm/pymap.cpython-39-x86_64-linux-gnu.so: undefined symbol: cudaMemcpyAsync

**Comment by yashbhalgat** [comment]
Hi, I am facing the same error when I run `bin/opensfm_run_all data/berlin`

@fabianschenk, any thoughts on this? Would really appreciate it!
