### ISSUE TITLE
ImportError: cannot import name 'pybundle' from partially initialized module 'opensfm'

### ISSUE THREAD

**Issue by YanaHontarenko** [mapillary/OpenSfM#902]
I tried to use the provided Dockerfile but it seems the library didn't install correctly.

`from opensfm import dataset`

The code above provided an error:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/project/opensfm/__init__.py", line 1, in <module>
    from opensfm import pybundle
ImportError: cannot import name 'pybundle' from partially initialized module 'opensfm' (most likely due to a circular import) (/opt/project/opensfm/__init__.py)
```
I didn't change anything in this Dockerfile and couldn't find answers in the issues.

**Comment by fabianschenk** [comment]
Hi @hontiky ,
can you try to get the newest version and simply try again.
Looking at the [commit history](https://github.com/mapillary/OpenSfM/commits/main), I think some of the builds were broken even though none had the issue you shared here.

Best,
Fabian

**Comment by Felipetoledo4815** [comment]
I have the same error when trying to execute:

`from opensfm import dataset`

from a python file. What can be done?

**Comment by seifertm** [comment]
I'm seeing the exact same issue on main (commit 193818dcd274fbc5763c654b0446df0aca696544) using Python3.10:
```
$ bin/opensfm --help
Traceback (most recent call last):
  File "/home/michael/OpenSfM/bin/opensfm_main.py", line 9, in <module>
    from opensfm import commands
  File "/home/michael/OpenSfM/opensfm/__init__.py", line 1, in <module>
    from opensfm import pybundle
ImportError: cannot import name 'pybundle' from partially initialized module 'opensfm' (most likely due to a circular import) (/home/michael/OpenSfM/opensfm/__init__.py)
```

The CI build seems to be green for that commit.

Is it worth reopening the bug?

**Comment by Matesanz** [comment]
It also happens with the Docker Image built using the dockerfile.

**Comment by Qiii77** [comment]
请问您找到解决办法了吗

**Comment by benlyazid** [comment]
any solution for this problem ?

**Comment by cjcjcj666** [comment]
bin/opensfm compute_depthmaps data/berlin
Traceback (most recent call last):
  File "C:\Users\cj\OneDrive\Desktop\output\OpenSfM\bin\opensfm_main.py", line 10, in <module>
    from opensfm import commands
  File "C:\Users\cj\OneDrive\Desktop\output\OpenSfM\opensfm\__init__.py", line 2, in <module>
    from opensfm import pybundle
ImportError: cannot import name 'pybundle' from partially initialized module 'opensfm' (most likely due to a circular import) (C:\Users\cj\OneDrive\Desktop\output\OpenSfM\opensfm\__init__.py)
Traceback (most recent call last):
  File "C:\Users\cj\OneDrive\Desktop\output\OpenSfM\bin\opensfm_main.py", line 10, in <module>
    from opensfm import commands
  File "C:\Users\cj\OneDrive\Desktop\output\OpenSfM\opensfm\__init__.py", line 2, in <module>
    from opensfm import pybundle
ImportError: cannot import name 'pybundle' from partially initialized module 'opensfm' (most likely due to a circular import) (C:\Users\cj\OneDrive\Desktop\output\OpenSfM\opensfm\__init__.py)

any solution for this problem ?
