### ISSUE TITLE
Errors on Control points annotation tool. File " gcp_manager.py", line 144, in load_from_file  measured_at=geo["measured_at"],

### ISSUE THREAD

**Issue by yuanyue** [mapillary/OpenSfM#913]
Hello,
I have builded OpenSfM on ubuntu successfully following the introduction. I want to try the Control points annotation tool,however，the following error occurred.Could someone tell me how to solver it?
![Uploading image.png…]()

**Comment by yuanyue** [comment]
(.venv) yy@LAPTOP-B0Q1K68R:~/source/OpenSfM$ python annotation_gui_gcp/main.py data/berlin
Traceback (most recent call last):
  File "annotation_gui_gcp/main.py", line 10, in <module>
    from annotation_gui_gcp.lib import GUI
ModuleNotFoundError: No module named 'annotation_gui_gcp'

**Comment by yuanyue** [comment]
Sorry,I got it. But there is another problem as follow and I‘m sure I can't solve it maybe.

Traceback (most recent call last):
  File "annotation_gui_gcp/main.py", line 263, in <module>
    app, args = init_ui()
  File "annotation_gui_gcp/main.py", line 252, in init_ui
    GUI.Gui(
  File "/home/yy/source/OpenSfM/annotation_gui_gcp/lib/GUI.py", line 38, in __init__
    self.load_gcps()
  File "/home/yy/source/OpenSfM/annotation_gui_gcp/lib/GUI.py", line 156, in load_gcps
    self.gcp_manager.load_from_file(filename)
  File "/home/yy/source/OpenSfM/annotation_gui_gcp/lib/gcp_manager.py", line 144, in load_from_file
    measured_at=geo["measured_at"],
KeyError: 'measured_at'
