### ISSUE TITLE
Build failure during akaze stage

### ISSUE THREAD

**Issue by marklit** [mapillary/OpenSfM#935]
The following was run on Ubuntu 20.04 LTS.

```bash
sudo apt install \
    libgflags-dev \
    libgoogle-glog-dev
cd ~
git clone --recursive https://github.com/mapillary/OpenSfM
cd OpenSfM
git submodule update --init --recursive
virtualenv ~/.opensfm
source ~/.opensfm/bin/activate
python3 -m pip install -r requirements.txt
python3 setup.py build
```

```
[ 34%] Building CXX object third_party/akaze/CMakeFiles/akaze.dir/lib/utils.cpp.o
[ 35%] Linking C static library libvl.a
[ 35%] Built target vl
[ 36%] Linking CXX static library libgtest.a
[ 36%] Built target gtest
[ 37%] Linking CXX static library libakaze.a
[ 37%] Built target akaze
make: *** [Makefile:101: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    build_c_extension()
  File "setup.py", line 54, in build_c_extension
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.
```

The actual error message from make is suppressed. If you need it, please let me know how I'd get it to print out to the CLI.

I did have a look at the build folder for akaze itself and it seems to build without issue. Bizzare.

```bash
cd ~/OpenSfM/cmake_build/third_party/akaze
make -j4
```

```
[100%] Built target akaze
```

**Comment by marklit** [comment]
I was missing ``python3-dev`` from my installed packages.

For anyone else having error messages suppressed:

```
cd cmake_build
make -j4
```

You'll see the entire error message.
