### ISSUE TITLE
OSError: No Images found in data/lund/images

### ISSUE THREAD

**Issue by Fsamhouri** [mapillary/OpenSfM#964]
I'm running into an error where I can't do reconstruction as it says that no images were found. However I changed nothing regarding the path of the sample data. 

```
/home/fsamhouri/3DReconstruction_Playground/OpenSfM/bin/opensfm_run_all data/lund
Traceback (most recent call last):
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/bin/opensfm_main.py", line 25, in <module>
    commands.command_runner(
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/commands/command_runner.py", line 34, in command_runner
    with dataset_factory(args.dataset, args.dataset_type) as data:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/bin/opensfm_main.py", line 17, in create_default_dataset_context
    dataset = DataSet(dataset_path)
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/dataset.py", line 52, in __init__
    self.load_image_list()
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/dataset.py", line 82, in load_image_list
    raise IOError("No Images found in {}".format(image_list_path))
OSError: No Images found in data/lund/images
```
Any possible reason why this is happening?

**Comment by fabianschenk** [comment]
Hi,
I think you're simply in the wrong directory. Also try to specify the complete path. Should be something like: `/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/data/lund/images`. If it still does not work, check the path again, check if a folder `data/lund/images` exists and if it contains images.

Best,
Fabian

**Comment by Fsamhouri** [comment]
The folder data/lund/images exists as it is example data. Here is the error when I go to the directory

```
fsamhouri@walle:~/3DReconstruction_Playground/OpenSfM/data/lund/images$ /home/fsamhouri/3DReconstruction_Playground/OpenSfM/bin/opensfm_run_all data/lund
Traceback (most recent call last):
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/bin/opensfm_main.py", line 25, in <module>
    commands.command_runner(
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/commands/command_runner.py", line 34, in command_runner
    with dataset_factory(args.dataset, args.dataset_type) as data:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/bin/opensfm_main.py", line 17, in create_default_dataset_context
    dataset = DataSet(dataset_path)
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/dataset.py", line 52, in __init__
    self.load_image_list()
  File "/home/fsamhouri/3DReconstruction_Playground/OpenSfM/opensfm/dataset.py", line 82, in load_image_list
    raise IOError("No Images found in {}".format(image_list_path))
OSError: No Images found in data/lund/images
```
![Screenshot from 2022-11-23 02-33-20](https://user-images.githubusercontent.com/60676580/203501725-065eccfd-b8ad-40d5-b16d-191b8bea4099.png)

Here is the image of the folder as well

**Comment by fabianschenk** [comment]
Please, follow the instructions in the [documentation](https://opensfm.org/docs/using.html) and run exactly the commands given. 
First, go to the correct directory:
```
cd /home/fsamhouri/3DReconstruction_Playground/OpenSfM/
```
then run the command as given by the documentation for either berlin or lund
```
bin/opensfm_run_all data/berlin
bin/opensfm_run_all data/lund
```
Take also some time to revisit the basic about relative vs. absolute paths. If you run from a folder `~/3DReconstruction_Playground/OpenSfM/data/lund/images` (like in your second example) then of course the relative `data/lund/images` does not exist because it's resolved as `~/3DReconstruction_Playground/OpenSfM/data/lund/images/data/lund/images`

**Comment by Fsamhouri** [comment]
Yes, I just managed to solve it. I misunderstood what you meant by specifying the path. Once I specified the path on data/lund to also go to images, it worked. Thanks for your help, Fabian!
